-- V20: Add South Metro Manila hubs
-- BGC, McKinley Hill, Taguig, Makati, Pasay, Pateros,
-- Muntinlupa, Paranaque, Las Pinas
-- Uses INSERT IGNORE to skip duplicates safely.

INSERT IGNORE INTO hubs (code, name, area, status, created_at, updated_at) VALUES

-- ── BGC: THE GRID (STREETS & AVENUES) ────────────────────────────────
('BGC_1ST_AVE',               'BGC 1st Avenue',                        'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_2ND_AVE',               'BGC 2nd Avenue',                        'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_3RD_AVE',               'BGC 3rd Avenue',                        'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_4TH_AVE',               'BGC 4th Avenue',                        'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_7TH_AVE',               'BGC 7th Avenue / The Fort Strip',       'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_8TH_AVE',               'BGC 8th Avenue',                        'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_10TH_AVE',              'BGC 10th Avenue',                       'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_11TH_AVE',              'BGC 11th Avenue',                       'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_24TH_ST',               'BGC 24th Street',                       'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_25TH_ST',               'BGC 25th Street',                       'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_26TH_ST',               'BGC 26th Street',                       'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_28TH_ST',               'BGC 28th Street',                       'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_30TH_ST',               'BGC 30th Street',                       'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_31ST_ST',               'BGC 31st Street',                       'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_34TH_ST',               'BGC 34th Street',                       'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_5TH_AVE_HUB',           '5th Avenue / 30th St Junction',         'Taguig',     'ACTIVE', NOW(6), NOW(6)),

-- ── BGC: MAJOR OFFICE TOWERS ─────────────────────────────────────────
('BGC_ONE_NEO',               'One/NEO (Net One)',                      'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_TWO_NEO',               'Two/NEO (Net Square)',                   'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_THREE_NEO',             'Three/NEO (Net Quad)',                   'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_FOUR_NEO',              'Four/NEO (Net Plaza)',                   'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_FIVE_NEO',              'Five/NEO (Net Cube)',                    'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_SIX_NEO',               'Six/NEO (Net Lima)',                     'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_SEVEN_NEO',             'Seven/NEO (Net Park)',                   'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_NET_PARK',              'Net Park / Net Lima Towers',             'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_FINANCE_CTR',           'The Finance Centre',                    'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_METROBANK_CTR',         'Metrobank Center',                      'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_W_CITY_CTR',            'W City Center',                         'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_W_5TH_AVE',             'W Fifth Avenue',                        'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_ARTHALAND',             'ArthaLand Century Pacific Tower',       'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_PSE_TOWER',             'Philippine Stock Exchange (PSE) Tower', 'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_MENARCO',               'Menarco Tower',                         'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_ONE_WORLD',             'One World Place',                       'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_ECOTOWER',              'Ecotower',                              'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_ORE_CENTRAL',           'Ore Central Building',                  'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_CORP_CTR',              'BGC Corporate Center 1 & 2',            'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_ST_LUKES',              'St. Lukes Medical Center BGC',          'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_GLOBE_TOWER',           'The Globe Tower',                       'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_JP_MORGAN',             'J.P. Morgan Chase & Co. Tower',         'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_GOOGLE_PH',             'Google Philippines (BCDA Iconic Tower)','Taguig',     'ACTIVE', NOW(6), NOW(6)),

-- ── BGC: RESIDENTIAL ─────────────────────────────────────────────────
('BGC_SERENDRA',              'Serendra (One & Two)',                  'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_PACIFIC_PLAZA',         'Pacific Plaza Towers',                  'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_ARYA',                  'Arya Residences',                       'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_ONE_MCKINLEY',          'One McKinley Place',                    'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_FORBESWOOD',            'Forbeswood Heights/Parklane',           'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_TRION',                 'The Trion Towers',                      'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_UPTOWN_RITZ',           'Uptown Ritz',                           'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_AVIDA_TURF',            'Avida Towers Turf BGC',                 'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_MARIDIEN',              'One & Two Maridien',                    'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_VERVE',                 'Verve Residences',                      'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_ONE_MARIDIEN',          'One Maridien / High Street South',      'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_SERENDRA_PIAZZA',       'Serendra Piazza (McKinley Pkwy)',       'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_AVIDA_CITYFLEX',        'Avida Cityflex / 7th Ave North',        'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_VERITERE',              'Veritere / Avida Towers 34th',          'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_LANDER_BGC',            'Landers Superstore BGC Uptown',         'Taguig',     'ACTIVE', NOW(6), NOW(6)),

-- ── BGC: HOTELS & LIFESTYLE ───────────────────────────────────────────
('BGC_SHANGRI_LA',            'Shangri-La at the Fort',                'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_GRAND_HYATT',           'Grand Hyatt Manila',                    'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_ASCOTT_BGC',            'Ascott Bonifacio Global City',          'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_SEDA_BGC',              'Seda BGC',                              'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_F1_HOTEL',              'F1 Hotel Manila',                       'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_BURGOS_CIRCLE',         'Burgos Circle / Forbes Town Center',    'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_MITSUKOSHI',            'Mitsukoshi BGC',                        'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_CENTRAL_SQUARE',        'Central Square (Bonifacio High St)',    'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_MIND_MUSEUM',           'The Mind Museum',                       'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_GRAND_HYATT_GATE',      'Grand Hyatt Residences Gate',           'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_TURF_BGC',              'Turf BGC (9th Avenue)',                 'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_S_AND_R_BGC',           'S&R BGC / 32nd St Corner',              'Taguig',     'ACTIVE', NOW(6), NOW(6)),

-- ── BGC: UPTOWN ───────────────────────────────────────────────────────
('BGC_UPTOWN_PARADE',         'Uptown Parade (Dining/Nightlife)',      'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_UPTOWN_TOWERS',         'Uptown Towers 1/2/3 (BPO Hub)',         'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_PARK_TRIANGLE',         'Park Triangle (Corporate & Mall)',      'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_VERITOWN_NORTH',        'Veritown North (Grand Hyatt Area)',     'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_KALAYAAN_BRIDGE',       'BGC-Ortigas Bridge (Luzon Side)',       'Taguig',     'ACTIVE', NOW(6), NOW(6)),

-- ── BGC: TRANSIT & GATEWAYS ───────────────────────────────────────────
('BGC_MARKET_MARKET_PUV',     'Market! Market! PUV Terminal',          'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_MCKINLEY_PARKWAY',      'McKinley Parkway / Aura Exit',          'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_SM_AURA_OFFICE',        'SM Aura Office Tower (McKinley Pkwy)', 'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_MCKINLEY_EXCHANGE',     'McKinley Exchange (EDSA/Ayala Hub)',    'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_C5_ELEVATED_EXIT',      'BGC C5 Elevated Ramp (Southbound)',     'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_32ND_ST_FLYOVER',       '32nd Street / Kalayaan Flyover',        'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_NORTH_GATE_ENTRY',      'North Gate / Kalayaan Ave Entry',       'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_LAWTON_5TH_AVE',        'Lawton Ave / 5th Ave Gate',             'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_KALAYAAN_GATEWAY',      'Kalayaan Ave / 32nd St Entry',          'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_ESSENSA',               'Essensa East Forbes Area',              'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_INFANTRY_RD',           'Infantry Road / Bayani Road Hub',       'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_BUTITI_ST',             'Butiti St (Park Triangle Area)',        'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_CYBER_SIGMA',           'Cyber Sigma (Lawton Ave Side)',         'Taguig',     'ACTIVE', NOW(6), NOW(6)),

-- ── BGC: INSTITUTIONAL ───────────────────────────────────────────────
('BGC_STI_ACADEMIC',          'STI Academic Center BGC',               'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('BGC_UNIVERSITY_PARK',       'University Parkway (ISM/BSM/STI)',      'Taguig',     'ACTIVE', NOW(6), NOW(6)),

-- ── MCKINLEY HILL ─────────────────────────────────────────────────────
('MKH_VENICE_GRAND_CANAL',    'Venice Grand Canal Mall Hub',           'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('MKH_UPPER_MCKINLEY',        'Upper McKinley Road (Corporate)',       'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('MKH_SCIENCE_HUB',           'Science Hub (Towers 1-4)',              'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('MKH_COMMERCE_SITE',         'Commerce & Industry Plaza',             'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('MKH_MORGAN_SUITES',         'Morgan Suites / Florence Way',          'Taguig',     'ACTIVE', NOW(6), NOW(6)),

-- ── TAGUIG: ARCA SOUTH & FTI ─────────────────────────────────────────
('TGG_ARCA_SOUTH_MAIN',       'Arca South (Main Transit Hub)',         'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('TGG_ONE_ARCA_SOUTH',        'One Arca South (Corporate Center)',     'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('TGG_SAVYA_FINANCIAL',       'Savya Financial Center (Arca South)',   'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('TGG_FTI_RECI_RD',           'FTI Reciprocity Road (Lower Bicutan)', 'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('TGG_LOWER_BICUTAN_HALL',    'Brgy. Lower Bicutan (Taguig Side)',     'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('TGG_CAYETANO_BLVD_C5',      'Cayetano Blvd (C5 Extension)',          'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('TGG_TENEMENT_TAGUIG',       'Taguig Tenement (Western Bicutan)',     'Taguig',     'ACTIVE', NOW(6), NOW(6)),

-- ── TAGUIG: C5 CORRIDOR & RESIDENTIAL ────────────────────────────────
('TGG_LEVI_MARIANO_HUB',      'Levi Mariano Ave / C5 Junction',        'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('TGG_GRACE_RESIDENCES',      'Grace Residences (Cayetano Blvd)',      'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('TGG_VISTA_MALL_TAGUIG',     'Vista Mall Taguig (Camella Colina)',    'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('TGG_ACACIA_ESTATES',        'Acacia Estates (Main Entrance)',        'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('TGG_PINAGSAMA_VILLAGE',     'Pinagsama Village (C5/Waterwood)',      'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('TGG_BCDA_VILLAGE',          'BCDA Village (C5/Pamplona)',            'Taguig',     'ACTIVE', NOW(6), NOW(6)),

-- ── TAGUIG: C6 & LAKESHORE ────────────────────────────────────────────
('TGG_C6_LAKESHORE_HUB',      'C6 Road / Lakeshore (Hagonoy)',         'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('TGG_LAKESHORE_HALL',        'Lakeshore Hall (Hagonoy / C6)',         'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('TGG_C6_TAGUIG_EXIT',        'C6 Road / Taguig Exit (Napindan)',      'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('TGG_NAPINDAN_BRIDGE',       'Napindan Bridge (Pasig Boundary)',      'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('TGG_TIPAS_CENTRAL',         'Brgy. Tipas / Poblacion Hub',           'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('TGG_BAMBANG_CHURCH',        'Bambang Church (Brgy. Bambang)',        'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('TGG_SAN_ANA_POBLACION',     'Sta. Ana / Taguig City University',     'Taguig',     'ACTIVE', NOW(6), NOW(6)),

-- ── TAGUIG: MILITARY & GOVERNMENT ────────────────────────────────────
('TGG_LAWTON_GATE_3',         'Lawton Ave Gate 3 (Nichols Hub)',       'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('TGG_LAWTON_GATE_5',         'Lawton Ave / Gate 5 (Cypress Hub)',     'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('TGG_BAYANI_ROAD_AFPOVAI',   'Bayani Road (AFPOVAI Gate 1)',          'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('TGG_HERITAGE_PARK_G',       'Heritage Park (C5 Gateway)',            'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('TGG_COMMAND_GENERAL',       'Command and General Staff College',     'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('TGG_PHIL_ARMY_OFFICERS',    'Philippine Army Officers Village',      'Taguig',     'ACTIVE', NOW(6), NOW(6)),

-- ── TAGUIG: TRANSIT NODES ─────────────────────────────────────────────
('TGG_BICUTAN_PNR_HUB',       'Bicutan PNR / SM Bicutan Transfer',     'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('TGG_ML_QUEZON_SOUTH',       'M.L. Quezon Ave (Taguig-Munti Ext)',    'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('TGG_WEST_BICUTAN_WSR',      'West Bicutan / WSR Junction',           'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('TGG_MCKINLEY_HILL_GATE',    'McKinley Hill / Lawton Gateway',        'Taguig',     'ACTIVE', NOW(6), NOW(6)),
('TGG_BGC_SOUTH_GATEWAY',     'BGC South Gate (McKinley Rd)',          'Taguig',     'ACTIVE', NOW(6), NOW(6)),

-- ── MAKATI: MAJOR THOROUGHFARES ───────────────────────────────────────
('MKT_AYALA_AVE',             'Ayala Avenue (Main Hub)',               'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_GIL_PUYAT',             'Gil Puyat Ave (Buendia)',               'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_MAKATI_AVE',            'Makati Avenue',                         'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_CHINO_ROCES',           'Chino Roces Ave (Pasong Tamo)',         'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_PASEO_ROXAS',           'Paseo de Roxas',                        'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_ARNAIZ_AVE',            'Arnaiz Avenue (Pasay Road)',            'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_AMORSOLO',              'Amorsolo Street',                       'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_JP_RIZAL',              'J.P. Rizal Avenue',                     'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_KALAYAAN',              'Kalayaan Avenue (Makati)',              'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_ESTRELLA',              'Estrella Street',                       'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_JUPITER',               'Jupiter Street',                        'Makati',     'ACTIVE', NOW(6), NOW(6)),

-- ── MAKATI: CORE CBD OFFICE TOWERS ───────────────────────────────────
('MKT_PBCOM_TOWER',           'PBCom Tower',                           'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_GT_TOWER',              'GT Tower International',                'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_RCBC_PLAZA',            'RCBC Plaza (Yuchengco Tower)',          'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_AYALA_TOWER_ONE',       'Ayala Tower One',                       'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_ZUellig_Bldg',          'Zuellig Building',                      'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_LKG_TOWER',             'LKG Tower',                             'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_ENTERPRISE_CTR',        'The Enterprise Center',                 'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_PACIFIC_STAR',          'Pacific Star Building',                 'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_AYALA_NORTH_EXCH',      'Ayala North Exchange',                  'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_6789_AYALA',            '6789 Ayala Avenue',                     'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_INSULAR_LIFE',          'Insular Life Building',                 'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_SALCEDO_VILL_PARK',     'Salcedo Village (Velazquez Park)',      'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_LEGAZPI_VILL_PARK',     'Legazpi Village (Washington SyCip)',    'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_VALERO_ST_HUB',         'Valero Street (Corporate Cluster)',     'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_KALAYAAN_AVE_HUB',      'Kalayaan Avenue / Makati Ave Junction', 'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_JP_RIZAL_PIVOT',        'J.P. Rizal / Makati Ave Pivot',         'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_H_V_DELA_COSTA',        'H.V. Dela Costa (Leviste St Junction)', 'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_AMORSOLO_CREEK_SIDE',   'Amorsolo St (Creek Side / Mile Long)', 'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_TORDESILLAS_SALCEDO',   'Tordesillas / Bautista (Salcedo)',      'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_VALERO_ACCESS_RD',      'Valero Access Road 4 (Loading Zone)',   'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_LEGASPI_ACTIVE_PARK',   'Legaspi Active Park (Rada St)',         'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_DELA_ROSA_BRIDGE',      'Dela Rosa Elevated Walkway (Exit 3)',   'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_DELA_ROSA_STOP',        'Dela Rosa Walkway (Loading Zone)',      'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_VALERO_STRAT_HUB',      'Valero St (Stratford/Corporate Ave)',   'Makati',     'ACTIVE', NOW(6), NOW(6)),

-- ── MAKATI: ROCKWELL & POBLACION ─────────────────────────────────────
('MKT_POWER_PLANT',           'Power Plant Mall (Rockwell)',           'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_ONE_ROCKWELL',          'One Rockwell (East & West)',            'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_PROSCENIUM',            'The Proscenium at Rockwell',            'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_PH_SEA_CTR',            'Phinma Plaza / Rockwell Hub',           'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_CENTURY_CITY',          'Century City / Trump Tower',            'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_CIRCUIT_MAKATI',        'Circuit Makati (Ayala Malls)',          'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_P_BURGOS',              'P. Burgos Street (Poblacion)',          'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_ROCKWELL_CENTER',       'Rockwell Center (Power Plant Mall)',    'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_POBLACION_MARKET',      'Poblacion Public Market',               'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_POBLACION_CENTRAL',     'Poblacion (A. Venue/P. Burgos Hub)',    'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_A_MABINI_POBLACION',    'A. Mabini St (Poblacion Heritage)',     'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_CIRCUIT_MAKATI_DROP',   'Circuit Makati (Riverfront Drive)',     'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_CIRCUIT_POWER_STATION', 'Circuit Makati (S&R / Powerhouse)',     'Makati',     'ACTIVE', NOW(6), NOW(6)),

-- ── MAKATI: SHOPPING, HOTELS & TRANSPORT ─────────────────────────────
('MKT_ONE_AYALA',             'One Ayala (Transport Terminal)',        'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_GLORIETTA',             'Glorietta (1-5 Area)',                  'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_GREENBELT',             'Greenbelt (1-5 Area)',                  'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_SM_MAKATI',             'SM Makati',                             'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_LANDMARK_MKT',          'Landmark Makati',                       'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_SHANGRI_LA_MKT',        'Makati Shangri-La',                     'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_PENINSULA_PH',          'The Peninsula Manila',                  'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_FAIRMONT_RAFFLES',      'Fairmont & Raffles Makati',             'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_AYALA_TRIANGLE',        'Ayala Triangle Gardens',                'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_WALK_WAY',              'Dela Rosa Walkway (Entrance)',          'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_GREENBELT_1_DRIVE',     'Greenbelt 1 (Paseo de Roxas Entry)',    'Makati',     'ACTIVE', NOW(6), NOW(6)),

-- ── MAKATI: VILLAGE GATES ─────────────────────────────────────────────
('MKT_MAGALLANES_HUB',        'Magallanes Village / SLEX Exit',        'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_MAGALLANES_VILLAGE',    'Magallanes Village (Main Gate)',        'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_DASMARINAS_GATE',       'Dasmarinas Village (Arnaiz Gate)',      'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_DASMARINAS_VILL_G',     'Dasmarinas Village (Pasay Rd Gate)',    'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_FORBES_PARK_GATE',      'Forbes Park (McKinley Gate)',           'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_SAN_LORENZO_GATE',      'San Lorenzo Village (Pasay Rd Gate)',   'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_URDANETA_VILL_GATE',    'Urdaneta Village (Ayala Ave Gate)',     'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_ALPHALAND_SOUTH',       'Alphaland Southgate (EDSA/Magallanes)','Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_ALPHALAND_SLEX',        'Alphaland Southgate (SLEX Ramp)',       'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_MAGALLANES_MRT_HUB',    'Magallanes MRT (Southbound Loading)',   'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_EDSA_MAGALLANES_TERM',  'Magallanes Interchange (SLEX/EDSA)',    'Makati',     'ACTIVE', NOW(6), NOW(6)),

-- ── MAKATI: TRANSPORT & PERIPHERY ────────────────────────────────────
('MKT_BUENDIA_SLEX',          'Buendia (Gil Puyat) / SLEX Entry',      'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_CHINO_ROCES_EXT',       'Chino Roces Ext (Kayamanan C)',         'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_CHINO_ROCES_SOUTH',     'Chino Roces Ext (Mantrade/SLEX)',       'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_CHINO_ROCES_PRC',       'Chino Roces / J.P. Rizal (PRC)',        'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_PASONG_TAMO_SHOPWISE',  'Shopwise Pasong Tamo Hub',              'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_PASONG_TAMO_EXT',       'Pasong Tamo Ext (Ecoplaza/BPO)',        'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_LA_FUERZA_HUB',         'La Fuerza Plaza (Chino Roces)',         'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_OSMENA_HWY_HUB',        'Osmeña Highway / San Andres Hub',       'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_GUADALUPE_FERRY',       'Guadalupe Ferry Station',               'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_GUADALUPE_MKT_HUB',     'Guadalupe Commercial Complex Hub',      'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_GUADALUPE_VIEJO',       'Guadalupe Viejo (EDSA/Power Plant)',    'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_ESTRELLA_EDSA_HUB',     'Estrella St / EDSA (Rockwell Entry)',   'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_ESTACION_ST',           'Estacion St (Pasay Road PNR)',          'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_CASH_AND_CARRY',        'Cash & Carry (Filmore St/Buendia)',     'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_ZOBEL_ROXAS_BOUNDARY',  'Zobel Roxas (Makati-Manila Boundary)', 'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_ZOBEL_ROXAS_NORTH',     'Zobel Roxas / South Superhighway',      'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_VITO_CRUZ_EXT_MKT',     'Vito Cruz Ext (Makati Side)',           'Makati',     'ACTIVE', NOW(6), NOW(6)),

-- ── MAKATI: BANGKAL, TEJEROS & NORTH-WEST ────────────────────────────
('MKT_EVANGELISTA_ST_MKT',    'Evangelista St (Bangkal Area)',         'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_EVANGELISTA_MAIN',      'Evangelista St (Bangkal Commercial)',   'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_PIO_DEL_PILAR_HUB',     'Pio Del Pilar (Washington St Hub)',     'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_PIO_DEL_PILAR_ZONE',    'Pio Del Pilar (Washington / Arnaiz)',   'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_TEJEROS_HUB',           'Brgy. Tejeros (Chino Roces North)',     'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_TEJEROS_BOUNDARY',      'Brgy. Tejeros (San Andres Boundary)',   'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_KALSADA_TEJEROS',       'Brgy. Tejeros (Kalsada St / PRC)',      'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_SAN_ISIDRO_HUB',        'Brgy. San Isidro (Dian/Buendia)',       'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_STA_ANA_RACETRACK',     'Sta. Ana (Circuit Makati / PRC)',       'Makati',     'ACTIVE', NOW(6), NOW(6)),

-- ── MAKATI: EMBO RESIDENTIAL ─────────────────────────────────────────
('MKT_PEMBO_MARKET',          'Pembo Market / Flower Farm Area',       'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_PEMBO_FLOWER_FARM',     'Pembo / Flower Farm Area',              'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_COMEMBO_HUB',           'Comembo / JP Rizal Ext Hub',            'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_COMEMBO_MARKET',        'Comembo Public Market Hub',             'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_COMEMBO_C5_RAMP',       'Comembo / C5 Elevated Ramp Hub',        'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_REMB_CENTRAL',          'Rembo Central / JP Rizal Ext',          'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_RIZAL_VILL_HUB',        'Rizal Village (Makati Side)',           'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_JP_RIZAL_EXT_HUB',      'J.P. Rizal Ext (West Rembo Hub)',       'Makati',     'ACTIVE', NOW(6), NOW(6)),
('MKT_PITOGO_CENTRAL',        'Brgy. Pitogo (BGC-Makati Border)',      'Makati',     'ACTIVE', NOW(6), NOW(6)),

-- ── PASAY: MOA COMPLEX & BAY CITY ────────────────────────────────────
('PSY_MOA_GLOBE',             'SM Mall of Asia (The Globe)',           'Pasay',      'ACTIVE', NOW(6), NOW(6)),
('PSY_MOA_ARENA',             'Mall of Asia Arena',                    'Pasay',      'ACTIVE', NOW(6), NOW(6)),
('PSY_SMX_CONVENTION',        'SMX Convention Center Manila',          'Pasay',      'ACTIVE', NOW(6), NOW(6)),
('PSY_ONE_ECOM',              'One E-Com Center',                      'Pasay',      'ACTIVE', NOW(6), NOW(6)),
('PSY_TWO_ECOM',              'Two E-Com Center',                      'Pasay',      'ACTIVE', NOW(6), NOW(6)),
('PSY_FIVE_ECOM',             'Five E-Com Center',                     'Pasay',      'ACTIVE', NOW(6), NOW(6)),
('PSY_CONRAD_MANILA',         'Conrad Manila / S-Maison',              'Pasay',      'ACTIVE', NOW(6), NOW(6)),
('PSY_IKEA_PASAY',            'IKEA Pasay City',                       'Pasay',      'ACTIVE', NOW(6), NOW(6)),
('PSY_SM_BY_THE_BAY',         'SM By The Bay (Amusement Park)',        'Pasay',      'ACTIVE', NOW(6), NOW(6)),
('PSY_MA_ROXAS_BLVD',         'Roxas Boulevard (Pasay Segment)',       'Pasay',      'ACTIVE', NOW(6), NOW(6)),

-- ── PASAY: NEWPORT CITY ───────────────────────────────────────────────
('PSY_NEWPORT_WORLD',         'Newport World Resorts (Resorts World)', 'Pasay',      'ACTIVE', NOW(6), NOW(6)),
('PSY_NEWPORT_MALL',          'Newport Mall',                          'Pasay',      'ACTIVE', NOW(6), NOW(6)),
('PSY_MARRIOTT_MANILA',       'Marriott Hotel Manila',                 'Pasay',      'ACTIVE', NOW(6), NOW(6)),
('PSY_SAVOY_HOTEL',           'Savoy Hotel Manila',                    'Pasay',      'ACTIVE', NOW(6), NOW(6)),
('PSY_BELMONT_HOTEL',         'Belmont Hotel Manila',                  'Pasay',      'ACTIVE', NOW(6), NOW(6)),

-- ── PASAY: TRANSPORT TERMINALS ────────────────────────────────────────
('PSY_MRT_TAFT',              'MRT-3 Taft Avenue Station',             'Pasay',      'ACTIVE', NOW(6), NOW(6)),
('PSY_LRT_EDSA',              'LRT-1 EDSA Station',                    'Pasay',      'ACTIVE', NOW(6), NOW(6)),
('PSY_VICTORY_LINER',         'Victory Liner Pasay Terminal',          'Pasay',      'ACTIVE', NOW(6), NOW(6)),
('PSY_PHILTRANCO',            'Philtranco Pasay Terminal',             'Pasay',      'ACTIVE', NOW(6), NOW(6)),
('PSY_FIVE_STAR_BUS',         'Five Star Bus Pasay Terminal',          'Pasay',      'ACTIVE', NOW(6), NOW(6)),
('PSY_DLTB_TERMINAL',         'DLTB Co. Pasay Terminal',               'Pasay',      'ACTIVE', NOW(6), NOW(6)),
('PSY_GEN_RODRIGO',           'Tramo / Gen. Rodrigo St Hub',           'Pasay',      'ACTIVE', NOW(6), NOW(6)),

-- ── PASAY: CULTURAL, INSTITUTIONAL & ROADS ───────────────────────────
('PSY_CCP_MAIN',              'Cultural Center of the Philippines',    'Pasay',      'ACTIVE', NOW(6), NOW(6)),
('PSY_PICC',                  'PICC (Convention Center)',              'Pasay',      'ACTIVE', NOW(6), NOW(6)),
('PSY_STAR_CITY',             'Star City (Amusement Park)',            'Pasay',      'ACTIVE', NOW(6), NOW(6)),
('PSY_WORLD_TRADE_CTR',       'World Trade Center Metro Manila',       'Pasay',      'ACTIVE', NOW(6), NOW(6)),
('PSY_GSIS_COMPLEX',          'GSIS Headquarters / Senate',            'Pasay',      'ACTIVE', NOW(6), NOW(6)),
('PSY_DFA_MAIN',              'DFA Aseana (Macapagal Blvd)',           'Pasay',      'ACTIVE', NOW(6), NOW(6)),
('PSY_MACAPAGAL_BLVD',        'Diosdado Macapagal Boulevard',          'Pasay',      'ACTIVE', NOW(6), NOW(6)),
('PSY_GIL_PUYAT_EXT',         'Sen. Gil Puyat Ave (Buendia) Ext',      'Pasay',      'ACTIVE', NOW(6), NOW(6)),
('PSY_FB_HARRISON',           'F.B. Harrison Street',                  'Pasay',      'ACTIVE', NOW(6), NOW(6)),
('PSY_DOMESTIC_RD',           'Domestic Road (NAIA T4 Area)',          'Pasay',      'ACTIVE', NOW(6), NOW(6)),
('PSY_ANDREWS_AVE',           'Andrews Avenue (Newport Side)',         'Pasay',      'ACTIVE', NOW(6), NOW(6)),

-- ── PATEROS ───────────────────────────────────────────────────────────
('PTR_TOWN_CENTER',           'Pateros Town Center (Municipal Hall)',  'Pateros',    'ACTIVE', NOW(6), NOW(6)),
('PTR_MARKET_WAWA',           'Pateros Public Market (Wawa)',          'Pateros',    'ACTIVE', NOW(6), NOW(6)),
('PTR_ALMEDA_ST',             'M. Almeda Street (Main Road)',          'Pateros',    'ACTIVE', NOW(6), NOW(6)),
('PTR_ROSALES_ST',            'P. Rosales Street',                     'Pateros',    'ACTIVE', NOW(6), NOW(6)),
('PTR_HERRERA_ST',            'B. Morcilla Street / Herrera St',       'Pateros',    'ACTIVE', NOW(6), NOW(6)),
('PTR_BRIDGE_MAKATI',         'Pateros-Makati Bridge (JP Rizal)',      'Pateros',    'ACTIVE', NOW(6), NOW(6)),
('PTR_BRIDGE_TAGUIG',         'Pateros-Taguig Boundary (Tuktukan)',    'Pateros',    'ACTIVE', NOW(6), NOW(6)),
('PTR_BRIDGE_PASIG',          'Pateros-Pasig Boundary (San Joaquin)', 'Pateros',    'ACTIVE', NOW(6), NOW(6)),
('PTR_C5_EXIT',               'Pateros / C5 Road Exit',                'Pateros',    'ACTIVE', NOW(6), NOW(6)),
('PTR_SAN_ROQUE',             'Brgy. San Roque / Herrera',             'Pateros',    'ACTIVE', NOW(6), NOW(6)),
('PTR_SAN_PEDRO',             'Brgy. San Pedro / Almeda',              'Pateros',    'ACTIVE', NOW(6), NOW(6)),
('PTR_SAN_VICENTE',           'Brgy. San Vicente Hub',                 'Pateros',    'ACTIVE', NOW(6), NOW(6)),
('PTR_SAN_JOSE',              'Brgy. San Jose / Martires',             'Pateros',    'ACTIVE', NOW(6), NOW(6)),
('PTR_AGUHO',                 'Brgy. Aguho Hub',                       'Pateros',    'ACTIVE', NOW(6), NOW(6)),
('PTR_MAGTANGGOL',            'Brgy. Magtanggol Hub',                  'Pateros',    'ACTIVE', NOW(6), NOW(6)),
('PTR_TABACALERA',            'Brgy. Tabacalera Hub',                  'Pateros',    'ACTIVE', NOW(6), NOW(6)),
('PTR_SANTO_ROSARIO',         'Brgy. Sto. Rosario-Kanluran',           'Pateros',    'ACTIVE', NOW(6), NOW(6)),
('PTR_CATHOLIC_SCHOOL',       'Pateros Catholic School Area',          'Pateros',    'ACTIVE', NOW(6), NOW(6)),
('PTR_TECHNOLOGICAL_COL',     'Pateros Technological College',         'Pateros',    'ACTIVE', NOW(6), NOW(6)),

-- ── MUNTINLUPA: ALABANG / FILINVEST ──────────────────────────────────
('ALABANG_VTX',               'VTX (Vista Terminal Exchange)',         'Muntinlupa', 'ACTIVE', NOW(6), NOW(6)),
('ALABANG_CENTRAL_STN',       'Alabang Central Station',               'Muntinlupa', 'ACTIVE', NOW(6), NOW(6)),
('NORTHGATE_CYBERZONE',       'Northgate Cyberzone',                   'Muntinlupa', 'ACTIVE', NOW(6), NOW(6)),
('ALABANG_COMMERCIAL_CTR',    'Alabang Commercial Center',             'Muntinlupa', 'ACTIVE', NOW(6), NOW(6)),
('CIVIC_PRIME',               'Civic Prime / Civic Drive',             'Muntinlupa', 'ACTIVE', NOW(6), NOW(6)),
('ENTRATA_ALABANG',           'Entrata Urban Complex / Crimson',       'Muntinlupa', 'ACTIVE', NOW(6), NOW(6)),
('COMMERCE_AVENUE',           'Commerce Avenue Hub',                   'Muntinlupa', 'ACTIVE', NOW(6), NOW(6)),
('FILINVEST_AXIS',            'Filinvest Axis Towers',                 'Muntinlupa', 'ACTIVE', NOW(6), NOW(6)),
('MUN_NORTHGATE_CYBER',       'Northgate Cyberzone (Main Pickup)',     'Muntinlupa', 'ACTIVE', NOW(6), NOW(6)),
('MUN_FILINVEST_AXIS',        'Filinvest Axis Towers (BPO Cluster)',   'Muntinlupa', 'ACTIVE', NOW(6), NOW(6)),
('MUN_WESTGATE_HUB',          'Westgate Center (Commerce Ave)',        'Muntinlupa', 'ACTIVE', NOW(6), NOW(6)),
('MUN_FESTIVAL_WATER_G',      'Festival Mall (Water Garden Side)',     'Muntinlupa', 'ACTIVE', NOW(6), NOW(6)),
('MUN_AAV_MADRIGAL_GATE',     'Ayala Alabang (Madrigal Gate)',         'Muntinlupa', 'ACTIVE', NOW(6), NOW(6)),
('MUN_AAV_CHAMPACA_GATE',     'Ayala Alabang (Champaca Gate)',         'Muntinlupa', 'ACTIVE', NOW(6), NOW(6)),
('MUN_AAV_ACACIA_GATE',       'Ayala Alabang (Acacia Gate)',           'Muntinlupa', 'ACTIVE', NOW(6), NOW(6)),
('MUN_AAV_COMMERCE_GATE',     'Ayala Alabang (Commerce Ave Gate)',     'Muntinlupa', 'ACTIVE', NOW(6), NOW(6)),
('MUN_ALABANG_HILLS_MAIN',    'Alabang Hills Village (Main Gate)',     'Muntinlupa', 'ACTIVE', NOW(6), NOW(6)),
('MUN_HILLSBOROUGH_GATE',     'Hillsborough Village Gate',             'Muntinlupa', 'ACTIVE', NOW(6), NOW(6)),
('MUN_ENCLAVE_ALABANG',       'The Enclave Alabang (Daang Hari)',      'Muntinlupa', 'ACTIVE', NOW(6), NOW(6)),
('MUN_ALABANG_400',           'Alabang 400 Village Gate',              'Muntinlupa', 'ACTIVE', NOW(6), NOW(6)),
('MUN_MADRIGAL_BUSINESS',     'Madrigal Business Park (Muntinlupa)',   'Muntinlupa', 'ACTIVE', NOW(6), NOW(6)),

-- ── MUNTINLUPA: RESIDENTIAL & BARANGAY ───────────────────────────────
('MUNTINLUPA_MEDICAL_CTR',    'Muntinlupa Medical Center / Centropolis','Muntinlupa','ACTIVE', NOW(6), NOW(6)),
('TUNASAN_HUB',               'Brgy. Tunasan / SM Center Side',        'Muntinlupa', 'ACTIVE', NOW(6), NOW(6)),
('POBLACION_MUNTINLUPA',      'Brgy. Poblacion / NBP Area',            'Muntinlupa', 'ACTIVE', NOW(6), NOW(6)),
('PUTATAN_HUB',               'Brgy. Putatan (City Hall Area)',        'Muntinlupa', 'ACTIVE', NOW(6), NOW(6)),
('BAYANAN_HUB',               'Brgy. Bayanan Hub',                     'Muntinlupa', 'ACTIVE', NOW(6), NOW(6)),
('CUPANG_HUB',                'Brgy. Cupang / West Service Road',      'Muntinlupa', 'ACTIVE', NOW(6), NOW(6)),
('SUCAT_MUNTINLUPA_STN',      'Sucat Muntinlupa (PNR/East Service)',   'Muntinlupa', 'ACTIVE', NOW(6), NOW(6)),
('ALABANG_400',               'Alabang 400 Village',                   'Muntinlupa', 'ACTIVE', NOW(6), NOW(6)),
('PACITA_BOUNDARY',           'Pacita Complex Boundary (Muntinlupa)', 'Muntinlupa', 'ACTIVE', NOW(6), NOW(6)),
('MCX_EXIT',                  'MCX (Muntinlupa-Cavite Expressway)',    'Muntinlupa', 'ACTIVE', NOW(6), NOW(6)),
('MUN_SOLDIERS_HILLS_1',      'Soldiers Hills 1 (Main Gate)',          'Muntinlupa', 'ACTIVE', NOW(6), NOW(6)),
('MUN_SOLDIERS_HILLS_2',      'Soldiers Hills 2 (Interior Hub)',       'Muntinlupa', 'ACTIVE', NOW(6), NOW(6)),
('MUN_KATARUNGAN_VILL',       'Katarungan Village (Poblacion)',        'Muntinlupa', 'ACTIVE', NOW(6), NOW(6)),
('MUN_SM_MUNTINLUPA',         'SM Muntinlupa (Tunasan)',               'Muntinlupa', 'ACTIVE', NOW(6), NOW(6)),
('MUN_TUNASAN_MARKET',        'Tunasan Public Market / National Rd',   'Muntinlupa', 'ACTIVE', NOW(6), NOW(6)),
('MUN_SUSANA_HEIGHTS',        'Susana Heights SLEX Exit/Entry',        'Muntinlupa', 'ACTIVE', NOW(6), NOW(6)),
('MUN_VICTORIA_HOMES_MAIN',   'Victoria Homes (Main Gate/Tunasan)',    'Muntinlupa', 'ACTIVE', NOW(6), NOW(6)),
('MUN_LINDENWOOD_RES',        'Lindenwood Residences (Susana Heights)','Muntinlupa', 'ACTIVE', NOW(6), NOW(6)),
('MUN_LAKEFRONT_PRESIDIO',    'The Lakefront (Presidio/Sucat)',        'Muntinlupa', 'ACTIVE', NOW(6), NOW(6)),
('MUN_POSADAS_SUCAT',         'Posadas Village (Sucat Gateway)',       'Muntinlupa', 'ACTIVE', NOW(6), NOW(6)),
('MUN_CUPANG_BRGY_HALL',      'Brgy. Cupang (Intermodal Hub)',         'Muntinlupa', 'ACTIVE', NOW(6), NOW(6)),
('MUN_SOUTH_GREENHEIGHTS',    'South Greenheights Village',            'Muntinlupa', 'ACTIVE', NOW(6), NOW(6)),
('MUN_NBP_SUNKEN_GARDEN',     'NBP Sunken Garden / Reservation Hub',   'Muntinlupa', 'ACTIVE', NOW(6), NOW(6)),
('MUN_PACIFIC_VILLAGE',       'Pacific Village (Lucena St Gate)',      'Muntinlupa', 'ACTIVE', NOW(6), NOW(6)),
('MUN_INTERCITY_HOMES',       'Intercity Homes (Cupang)',              'Muntinlupa', 'ACTIVE', NOW(6), NOW(6)),
('MUN_SOUTHRIDGE_GATE',       'Southridge Village (Main Gate)',        'Muntinlupa', 'ACTIVE', NOW(6), NOW(6)),
('MUN_SANTANA_GROVE',         'Santana Grove (Soreena Ave)',           'Muntinlupa', 'ACTIVE', NOW(6), NOW(6)),
('MUN_PARKLANE_TUNASAN',      'Parklane Subd (Tunasan Interior)',      'Muntinlupa', 'ACTIVE', NOW(6), NOW(6)),
('MUN_BAGONG_TANYAG_HUB',     'Brgy. Bagong Tanyag (ESR Side)',        'Muntinlupa', 'ACTIVE', NOW(6), NOW(6)),

-- ── MUNTINLUPA: SERVICE ROADS ─────────────────────────────────────────
('MUN_WSR_TRIANGLE_7',        'Triangle 7 (West Service Road)',        'Muntinlupa', 'ACTIVE', NOW(6), NOW(6)),
('MUN_WSR_40_KNOTS',          '40 Knots / West Service Rd Hub',        'Muntinlupa', 'ACTIVE', NOW(6), NOW(6)),
('MUN_WSR_KAIJO',             'Kaijo St / West Service Road',          'Muntinlupa', 'ACTIVE', NOW(6), NOW(6)),
('MUN_WSR_ALABANG_EXIT',      'Alabang Exit / West Service Rd Hub',    'Muntinlupa', 'ACTIVE', NOW(6), NOW(6)),
('MUN_ESR_BAGONG_TANYAG',     'Bagong Tanyag (Munti-Taguig Border)',   'Muntinlupa', 'ACTIVE', NOW(6), NOW(6)),
('MUN_ESR_SUCAT_INTER',       'East Service Road / Sucat Interchange', 'Muntinlupa', 'ACTIVE', NOW(6), NOW(6)),
('MUN_ESR_SUCAT_TERM',        'East Service Rd / Sucat PUV Terminal',  'Muntinlupa', 'ACTIVE', NOW(6), NOW(6)),
('MUN_WSR_B_MAG_AREA',        'B-Mag Area (West Service Road)',        'Muntinlupa', 'ACTIVE', NOW(6), NOW(6)),

-- ── MUNTINLUPA: TRANSIT & BOUNDARIES ─────────────────────────────────
('MUN_MCX_JUNCTION',          'MCX / SLEX Interchange Hub',            'Muntinlupa', 'ACTIVE', NOW(6), NOW(6)),
('MUN_DAANG_HARI_MUNTI',      'Daang Hari Rd (Muntinlupa Segment)',    'Muntinlupa', 'ACTIVE', NOW(6), NOW(6)),
('MUN_SUCAT_PNR_STATION',     'Sucat PNR Station (East Service Rd)',   'Muntinlupa', 'ACTIVE', NOW(6), NOW(6)),
('MUN_TUNASAN_CITY_LIMIT',    'Tunasan City Limit (San Pedro)',        'Muntinlupa', 'ACTIVE', NOW(6), NOW(6)),

-- ── MUNTINLUPA: SCHOOLS & INSTITUTIONAL ──────────────────────────────
('SAN_BEDA_ALABANG',          'San Beda College Alabang',              'Muntinlupa', 'ACTIVE', NOW(6), NOW(6)),
('DE_LA_SALLE_ZOBEL',         'De La Salle Santiago Zobel',            'Muntinlupa', 'ACTIVE', NOW(6), NOW(6)),
('FEU_ALABANG',               'FEU Alabang',                           'Muntinlupa', 'ACTIVE', NOW(6), NOW(6)),
('RESEARCH_INST_MED',         'RITM (Research Inst. for Tropical Med)','Muntinlupa', 'ACTIVE', NOW(6), NOW(6)),
('MUN_CITY_HALL_MUNTI',       'Muntinlupa City Hall (Main)',           'Muntinlupa', 'ACTIVE', NOW(6), NOW(6)),
('MUN_OSMUN_HOSPITAL',        'Ospital ng Muntinlupa (OsMun)',         'Muntinlupa', 'ACTIVE', NOW(6), NOW(6)),

-- ── PARANAQUE: COMMERCIAL & ENTERTAINMENT ────────────────────────────
('PRQ_SOLAIRE',               'Solaire Resort & Casino',               'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_CITY_OF_DREAMS',        'City of Dreams Manila',                 'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_OKADA',                 'Okada Manila',                          'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_ASEANA_SQUARE',         'Aseana Square / Aseana City',           'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_PARACAL_RD',            'Paracal Road (Aseana Area)',            'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_NAIA_T1',               'NAIA Terminal 1 (Pasay/PRQ Boundary)', 'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_NAIA_T2',               'NAIA Terminal 2 (Centennial)',          'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_BACLARAN_CHURCH',       'Baclaran Church (Redemptorist)',        'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_BACLARAN_CHURCH_HUB',   'Baclaran Church / Redemptorist Rd',     'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_BACLARAN_LRT',          'Baclaran LRT Station Area',             'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_CITY_HALL',             'Paranaque City Hall',                   'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_PATTS',                 'PATTS College of Aeronautics',          'Paranaque',  'ACTIVE', NOW(6), NOW(6)),

-- ── PARANAQUE: SUCAT & BICUTAN ────────────────────────────────────────
('PRQ_SUCAT_EVANGELISTA',     'Sucat Road / Evangelista St',           'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_WALTMART_SUCAT',        'Waltermart Sucat',                      'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_BICUTAN_WSR',           'Bicutan West Service Road Hub',         'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_BICUTAN_ESR',           'Bicutan East Service Road Hub',         'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_BICUTAN_INTERCHANGE',   'Bicutan Interchange (SLEX Exit)',       'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_SUCAT_INTERCHANGE',     'Sucat Interchange (SLEX Exit)',         'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_NINOY_AQUINO_AVE',      'Ninoy Aquino Ave (Airport Corridor)',   'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_SUCAT_PALENGKE',        'Sucat Public Market (Palengke)',        'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_LRT_DR_SANTOS',         'LRT-1 Dr. Santos (Sucat) Station',      'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_SUCAT_STATION_PNR',     'Sucat PNR Station Area',                'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_SM_SUCAT_TERMINAL',     'SM Sucat PUV Terminal (Building B)',    'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_BICUTAN_ENTRY_SOUTH',   'Bicutan SLEX Southbound Entry',         'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_SUCAT_ENTRY_NORTH',     'Sucat SLEX Northbound Entry',           'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_SKYWAY_SUCAT_EXIT',     'Skyway Sucat Exit Ramp (PRQ)',          'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_BICUTAN_SLEX_EXIT',     'Bicutan Exit / DOST Boundary',          'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_SUCAT_SKYWAY_RAMP',     'Sucat Skyway On-Ramp (Northbound)',     'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_DONA_SOLEDAD_SM',       'Doña Soledad / SM Bicutan Junction',    'Paranaque',  'ACTIVE', NOW(6), NOW(6)),

-- ── PARANAQUE: BF HOMES ───────────────────────────────────────────────
('PRQ_BF_ELIZALDE',           'BF Homes (Elizalde Ave)',               'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_BF_AGUIRRE',            'BF Homes (Aguirre Ave Hub)',            'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_BF_NORTH_WEST',         'BF Homes North West',                   'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_BF_HOMES_PH_1',         'BF Homes Phase 1 / Tropical',           'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_BF_HOMES_PH_3',         'BF Homes Phase 3 / Aguirre',            'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_BF_HOMES_CONCHA',       'Concha Cruz / BF Homes Gate',           'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_BF_HOMES_TROPICAL',     'Tropical Avenue / BF Homes',            'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_BF_HOMES_SOUTHVILLE',   'Southville / BF International Area',    'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_BF_EL_GRANDE',          'El Grande Ave / BF Homes',              'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_BF_SOUTH_VALLEY',       'South Valley / BF Homes Extension',     'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_BF_TROPICAL_AVE',       'Tropical Avenue (BF North)',            'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_BF_NORTH_GATE',         'BF Homes North (Lopez/Sucat Gate)',     'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_BF_AGUIRRE_INTERIOR',   'Aguirre Ave / Tirona St Junction',      'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_TIRONA_ST_HUB',         'Tirona St / BF Homes Interior',         'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_TROPICAL_PALMS',        'Tropical Palms / BF Homes West',       'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_CAA_ROAD_MAIN',         'CAA Road / BF International Hub',      'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_SOUTHVILLE_INTL',       'Southville Intl / Luxembourg St',       'Paranaque',  'ACTIVE', NOW(6), NOW(6)),

-- ── PARANAQUE: RESIDENTIAL SUBDIVISIONS ──────────────────────────────
('PRQ_MULTINATIONAL_GATE',    'Multinational Village Main Gate',       'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_MOONWALK_GATE',         'Moonwalk Village Gate 1 & 2',           'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_MOONWALK_TALABA',       'Moonwalk (Talaba Street Hub)',          'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_MOONWALK_PH2_GATE',     'Moonwalk Phase 2 / Armstrong Gate',     'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_ARMSTRONG_AVE',         'Armstrong Ave / Moonwalk Hub',          'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_UNITED_PRQ',            'United Paranaque (UP1/UP2/UP3)',        'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_UNITED_PRQ_ESTATES',    'United Parañaque Estates (Ph 1-3)',     'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_UNITED_PRQ_1',          'United Parañaque 1 (SLEX Frontage)',    'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_NOMO_SUCAT',            'NOMO / Vista Mall Sucat',               'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_NOMO_TERMINAL',         'NOMO / PITX Transfer Hub (PRQ Side)',   'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_MARINA_BAY',            'Marina Bay Town',                       'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_MERVILLE_GATE',         'Merville Village (Main Gate)',          'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_MERVILLE_ADVENTIST',    'Merville / Adventist School Hub',       'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_MERVILLE_ADVENT',       'Adventist School / Merville',           'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_MARCELLO_GREEN_VILL',   'Marcelo Green Village (ESR Gate)',      'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_MARCELO_GREEN_PH1',     'Marcelo Green Phase 1 / ESR',           'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_SUN_VALLEY_PROPER',     'Sun Valley Subdivision (Brgy Hall)',    'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_SEVERINA_DIAMOND',      'Severina Diamond / West Service Rd',    'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_GATCHALIAN_HUB',        'Gatchalian Subdivision (Main)',         'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_IRENEVILLE',            'Ireneville Subdivision (Sucat)',        'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_SOUTH_ADRIATIC_ST',     'South Adriatic St / Better Living',     'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_VISTA_MALL_PRQ',        'Vista Mall Global South (PRQ side)',    'Paranaque',  'ACTIVE', NOW(6), NOW(6)),

-- ── PARANAQUE: BETTER LIVING ─────────────────────────────────────────
('PRQ_BETTER_LIVING_MAIN',    'Better Living (Doña Soledad Main)',     'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_BETTER_LIVING_PH3',     'Better Living Phase 3 (France St)',     'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_BETTER_LIVING_PH4',     'Better Living Phase 4 (Woodridge)',     'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_BETTER_LIVING_ANNEX',   'Better Living / Annex 35 Hub',          'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_ANNEX_35_HUB',          'Annex 35 / Better Living Interior',     'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_DON_BOSCO_CHURCH',      'Don Bosco Church / Sun Valley',         'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_DON_BOSCO_MAIN',        'Don Bosco (Better Living Gate)',        'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_EURO_VILLAGE',          'Eurofarma / United Hills',              'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_ZION_ROAD',             'Zion Road / Better Living Interior',    'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_ZION_ROAD_HUB',         'Zion Road / Better Living Gateway',     'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_MALUGAY_ST',            'Malugay St (Better Living Gate)',       'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_MALUGAY_GATE',          'Malugay St (Better Living Entry)',      'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_WOOD_RIDGE',            'Woodridge / Better Living Phase 4',     'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_JERUSALEM_ST',          'Jerusalem St / Better Living',          'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_MILAN_ST',              'Milan St / Better Living Phase 1',      'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_MARCELLA_ST',           'Marcella St / Multinational Village',   'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_VIVA_HOMES',            'Viva Homes / Better Living',            'Paranaque',  'ACTIVE', NOW(6), NOW(6)),

-- ── PARANAQUE: SAN ANTONIO & SUCAT INTERIOR ──────────────────────────
('PRQ_SAN_ANTONIO_VALLEY',    'San Antonio Valley 1 (Brgy Hall)',      'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_SAN_ANTONIO_VILL_5',    'San Antonio Valley 5 (Gate)',           'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_KABIHASNAN_INTERIOR',   'Kabihasnan / San Dionisio Hub',         'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_LOPEZ_VILLAGE',         'Lopez Village (Commercial)',            'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_LOPEZ_VILLAGE_MAIN',    'Lopez Village (Main Commercial)',       'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_SAN_ISIDRO_HUB',        'Brgy. San Isidro / Lopez',              'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_PATIO_MADRIGAL',        'Patio Madrigal / Roxas Blvd Side',      'Paranaque',  'ACTIVE', NOW(6), NOW(6)),

-- ── PARANAQUE: SERVICE ROADS ─────────────────────────────────────────
('PRQ_WSR_SUN_VALLEY',        'West Service Road / Sun Valley Gate',   'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_WSR_ASTRA',             'West Service Road / Astra',             'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_WSR_KNOTS',             'West Service Road / 40 Knots',          'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_WSR_EDISON_AVE',        'Edison Ave / West Service Road',        'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_WSR_EDISON_CORP',       'Edison Ave / West Service Rd (BPO)',    'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_KM_18_WSR',             'KM 18 West Service Road (Industrial)',  'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_ESR_MARCELO_GREEN',     'East Service Road / Marcelo Green',     'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_ESR_UNITED_PRQ',        'East Service Road / United Parañaque',  'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_ESR_PRYCE_GAS',         'East Service Rd / Pryce Gas Hub',       'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_KM_21_ESR',             'KM 21 East Service Road (Bicutan)',     'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_SOUTH_METRO_GATE',      'South Metro Gate / West Service Rd',    'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_K_POINT_HUB',           'K-Point / West Service Road',           'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_VALLEY_VIEW_C5',        'Valley View Residences (C5 Ext)',       'Paranaque',  'ACTIVE', NOW(6), NOW(6)),

-- ── PARANAQUE: COASTAL & AIRPORT ─────────────────────────────────────
('PRQ_COASTAL_PLAZA',         'Coastal Plaza / Cavitex Entry',         'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_PITX_TRANSFER_NODE',    'PITX / Parañaque Entry Point',          'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_QUIRINO_AVE_TAMBO',     'Quirino Ave (Tambo / NAIA Road)',        'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_TAMBO_HUB',             'Brgy. Tambo / Quirino Ave Hub',         'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_LA_HUERTA',             'Brgy. La Huerta / Coastal Road Hub',    'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_LA_HUERTA_BRIDGE',      'La Huerta / Parañaque River Bridge',    'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_DON_GALO_HUB',          'Brgy. Don Galo (Coastal Side)',         'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_NAIA_RD_TERMINAL_1',    'NAIA Terminal 1 (Parañaque Side)',      'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_AIRPORT_VILLAGE',       'Airport Village / MIA Road',            'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_DUTY_FREE_HUB',         'Duty Free Fiestamall / NAIA Rd',        'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_STO_NINO_HUB',          'Brgy. Sto. Niño (Pasay Boundary)',      'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_GLOBAL_SOUTH_MALL',     'Global South / Villar Sipag Hub',       'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_C5_EXT_FLYOVER',        'C5 Extension Flyover (Merville Side)', 'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_C5_EXT_SHELL',          'C5 Extension (Shell/Commercial Hub)',   'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_CARLOS_P_GARCIA',       'C.P. Garcia Ave / Pulang Lupa Uno',     'Paranaque',  'ACTIVE', NOW(6), NOW(6)),

-- ── PARANAQUE: SCHOOLS & MEDICAL ─────────────────────────────────────
('PRQ_OLIVAREZ_COLLEGE',      'Olivarez College Parañaque',            'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_OLIVAREZ_HOSPITAL',     'Olivarez General Hospital',             'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_PREMIERE_MED_CTR',      'Medical Center Parañaque (Sucat)',      'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_MANILA_MEMORIAL',       'Manila Memorial Park Gate (Sucat)',     'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_LOYOLA_MEMORIAL',       'Loyola Memorial Park (Sucat)',          'Paranaque',  'ACTIVE', NOW(6), NOW(6)),
('PRQ_ST_ANDREW_SCHOOL',      'St. Andrews School Area',               'Paranaque',  'ACTIVE', NOW(6), NOW(6)),

-- ── LAS PINAS: COMMERCIAL ─────────────────────────────────────────────
('LP_SM_CENTER',              'SM Center Las Piñas',                   'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_VISTA_MALL',             'Vista Mall Las Piñas',                  'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_LANDMARK_ALABANG_W',     'Landmark / Alabang West',               'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_STAR_AVENUE',            'C.V. Starr Avenue / Philamlife',        'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_VISTA_GLOBAL_SOUTH',     'Vista Global South / C5 Ext',           'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_SOUTH_MALL_TERMINAL',    'SM South Mall (PUV Terminal Hub)',      'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),

-- ── LAS PINAS: BF HOMES & SUBDIVISIONS ───────────────────────────────
('LP_BF_CAA_GATE',            'BF International / CAA Gate',           'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_BF_RESORT_DRIVE',        'BF Resort Drive (Main Hub)',            'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_BF_TROPICAL_PALMS',      'BF Homes Tropical Palms Area',          'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_BF_SOUTH_VILLE',         'Southville International School Area',  'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_BF_ALMANZA_MAIN',        'BF Almanza Main Gate',                  'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_BF_ALMANZA_REGALADO',    'Regalado St / BF Almanza Hub',          'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_BF_RESORT_CLUBHOUSE',    'BF Resort Village Clubhouse Area',      'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_BF_RESORT_ONX',          'Onix St / BF Resort (Commercial)',      'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_BF_THAI_HUB',            'BF Thai / Tropical Avenue Hub',         'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_ENCLAVE_ALABANG',        'The Enclave Alabang (Almanza Dos)',     'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_PILAR_EXECUTIVE',        'Pilar Executive Village Gate',          'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_GREAT_CHURCH_LP',        'The Great Church / BF Resort Hub',      'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_PILAR_VILLAGE',          'Pilar Village (Main Gate/Commercial)',  'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_PILAR_VILLAGE_SOUTH',    'Pilar Village (South Gate / Almanza)', 'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_PILAR_CHURCH_HUB',       'Holy Family Parish / Pilar Village',    'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_TS_CRUZ_GATE',           'T.S. Cruz Subdivision Gate',            'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_MOONWALK_LP',            'Moonwalk Village (Las Piñas)',          'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_MOONWALK_LP_INTERIOR',   'Moonwalk Village Ph 2 (Las Piñas)',     'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_MANUELA_VILLAGE',        'Manuela Subdivision (Pamplona)',        'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_MANUELA_1_HUB',          'Manuela 1 / Real St Gateway',           'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_MANUELA_4_GATE',         'Manuela 4 Gate (Pamplona Tres)',        'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_GOLDEN_GATE',            'Golden Gate Subdivision',               'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_GOLDEN_GATE_LP',         'Golden Gate Subd (Talon Tres)',         'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_VERA_VILLE',             'Vera Ville (Various Phases)',           'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_VERAVILLE_HUB',          'Veraville Homes (Various Clusters)',   'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_CAA_MAIN_HUB',           'Brgy. CAA / BF International Hub',      'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_CAA_RD_HUB',             'C.A.A. Road / BF International',        'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_CASIMIRO_VILLAGE',       'Casimiro Village (Main Gate)',          'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_PAMPLONA_CENTRAL',       'Pamplona Uno / Central Hub',            'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),

-- ── LAS PINAS: ROADS & JUNCTIONS ─────────────────────────────────────
('LP_ZAPOTE_BRIDGE',          'Zapote Bridge (Las Pinas-Bacoor)',      'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_CASIMIRO_AVE',           'Casimiro Avenue / Diego Cera',          'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_VILLAREAL_ST',           'Villareal St / Parañaque Boundary',     'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_FRUTO_SANTOS',           'Fruto Santos Avenue',                   'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_TALABA_DIVERSION',       'Las Piñas-Talaba Diversion Road',       'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_DIEGO_CERA_AVE',         'Diego Cera Avenue (General)',           'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_MARCOS_ALVAREZ_HUB',     'Marcos Alvarez Ave / Moonwalk Hub',     'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_MARCOS_ALVAREZ_RD',      'Marcos Alvarez Avenue Hub',             'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_MARCOS_ALVAREZ_ENTRY',   'Marcos Alvarez / Alabang-Zapote Rd',    'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_C5_EXT_FLYOVER',         'C5 Extension / Quirino Ave Flyover',    'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_C5_EXT_LP_EXIT',         'C5 Extension / Las Piñas Exit',         'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_VILLAR_SIPAG',           'Villar SIPAG Center',                   'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_VILLAR_CITY_LP',         'Villar City (Las Piñas Entrance)',      'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_GULOT_AREA',             'Gulot / Pulanglupa Uno',                'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_CARMEL_GATE',            'Carmel Village Gate (C5 Ext)',          'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_GLOBAL_SOUTH_C5',        'Global South / C5 Ext Gateway',         'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_PULANGLUPA_UNO',         'Pulang Lupa Uno / Quirino Ave',         'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_TRAMO_LP_HUB',           'Tramo / Padre Diego Cera Ave',          'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_QUIRINO_AVE_LP',         'Quirino Avenue (Las Piñas Segment)',    'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_SMC_GLOBAL_SOUTH',       'SMC Global South (Redoliant Area)',     'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_ZAPOTE_KALIN_GATE',      'Zapote Kalinisan Junction',             'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_FLYOVER_ALABANG_ZAP',    'Alabang-Zapote Flyover (Casimiro)',     'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_CONCHA_CRUZ_DRIVE',      'Concha Cruz Drive (Madrigal Boundary)', 'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_LONGOS_FLYOVER',         'Longos Flyover / Talaba Junction',      'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),

-- ── LAS PINAS: ALMANZA & DAANG HARI ──────────────────────────────────
('LP_ALMANZA_UNO_HUB',        'Almanza Uno (Commercial Center)',       'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_ALMANZA_DOS_HUB',        'Almanza Dos / Daang Hari Entry',        'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_DAANG_HARI_LP_EXIT',     'Daang Hari Road (Las Piñas Side)',      'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_EVIA_LIFESTYLE_LP',      'Evia Lifestyle Center (LP Boundary)',   'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_FORREST_A_LP',           'Forresta (Villar Land) / Daang Hari',   'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_SOMERSET_LP',            'Somerset (Almanza Dos)',                'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),

-- ── LAS PINAS: TALON ──────────────────────────────────────────────────
('LP_TALON_KUATRO_HUB',       'Talon Kuatro / J. Aguilar Ave',         'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_TALON_SINGKO_HUB',       'Talon Singko / Marcos Alvarez Ext',     'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_TALON_2_COMMERCIAL',     'Talon Dos (Commercial Area)',           'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),

-- ── LAS PINAS: MEDICAL & INSTITUTIONAL ───────────────────────────────
('LP_BAMBOO_ORGAN',           'Bamboo Organ Church (St. Joseph)',      'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_SARAO_MOTORS',           'Sarao Motors Factory Hub',              'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_GEN_HOSPITAL',           'Las Piñas General Hospital',            'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_LAS_PINAS_DOCTORS',      'Las Piñas Doctors Hospital',            'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_LP_DOCTORS_HOSP',        'Las Piñas Doctors Hospital (CAA Rd)',   'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_UPHSD_CAMPUS',           'Perpetual Help (University/Hospital)',  'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_PERP_HELP_MED',          'UPH - Dalta Medical Center',            'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_SOUTHVILLE_INTL',        'Southville Intl School (Luxembourg)',   'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_ST_FRANCIS_ASSISI',      'St. Francis of Assisi College LP',      'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_CHRIST_THE_KING_LP',     'Christ the King (Pamplona) Hub',        'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_CITY_HALL',              'Las Piñas City Hall',                   'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_STI_LAS_PINAS',          'STI College Las Piñas',                 'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_POPE_JOHN_PAUL',         'Pope John Paul II Hospital',            'Las Pinas',  'ACTIVE', NOW(6), NOW(6)),
('LP_ST_DOMINIC',             'St. Dominic Medical Center (Boundary)', 'Las Pinas',  'ACTIVE', NOW(6), NOW(6));
