-- V21: Hub aliases for V20 South Metro Manila hubs
-- Aliases are lowercase to match HubMatcher search behavior.
-- Uses INSERT IGNORE to skip duplicates safely.
-- All aliases verified against existing hub_aliases to avoid conflicts.
-- Compatible with MySQL 8.0+

INSERT IGNORE INTO hub_aliases (hub_id, alias)
SELECT h.id, v.alias
FROM hubs h
INNER JOIN (
  SELECT 'BGC_1ST_AVE' AS hub_code, 'bgc 1st' AS alias
  UNION ALL SELECT 'BGC_1ST_AVE', '1st ave bgc'
  UNION ALL SELECT 'BGC_1ST_AVE', 'bgc first avenue'
  UNION ALL SELECT 'BGC_2ND_AVE', 'bgc 2nd'
  UNION ALL SELECT 'BGC_2ND_AVE', '2nd ave bgc'
  UNION ALL SELECT 'BGC_2ND_AVE', 'bgc second avenue'
  UNION ALL SELECT 'BGC_3RD_AVE', 'bgc 3rd'
  UNION ALL SELECT 'BGC_3RD_AVE', '3rd ave bgc'
  UNION ALL SELECT 'BGC_3RD_AVE', 'bgc third avenue'
  UNION ALL SELECT 'BGC_4TH_AVE', 'bgc 4th'
  UNION ALL SELECT 'BGC_4TH_AVE', '4th ave bgc'
  UNION ALL SELECT 'BGC_4TH_AVE', 'bgc fourth avenue'
  UNION ALL SELECT 'BGC_7TH_AVE', 'bgc 7th'
  UNION ALL SELECT 'BGC_7TH_AVE', '7th ave bgc'
  UNION ALL SELECT 'BGC_7TH_AVE', 'fort strip bgc ave'
  UNION ALL SELECT 'BGC_7TH_AVE', 'bgc seventh avenue'
  UNION ALL SELECT 'BGC_8TH_AVE', 'bgc 8th'
  UNION ALL SELECT 'BGC_8TH_AVE', '8th ave bgc'
  UNION ALL SELECT 'BGC_8TH_AVE', 'bgc eighth avenue'
  UNION ALL SELECT 'BGC_10TH_AVE', 'bgc 10th'
  UNION ALL SELECT 'BGC_10TH_AVE', '10th ave bgc'
  UNION ALL SELECT 'BGC_11TH_AVE', 'bgc 11th'
  UNION ALL SELECT 'BGC_11TH_AVE', '11th ave bgc'
  UNION ALL SELECT 'BGC_24TH_ST', 'bgc 24th'
  UNION ALL SELECT 'BGC_24TH_ST', '24th st bgc'
  UNION ALL SELECT 'BGC_25TH_ST', 'bgc 25th'
  UNION ALL SELECT 'BGC_25TH_ST', '25th st bgc'
  UNION ALL SELECT 'BGC_26TH_ST', 'bgc 26th'
  UNION ALL SELECT 'BGC_26TH_ST', '26th st bgc'
  UNION ALL SELECT 'BGC_28TH_ST', 'bgc 28th'
  UNION ALL SELECT 'BGC_28TH_ST', '28th st bgc'
  UNION ALL SELECT 'BGC_30TH_ST', 'bgc 30th'
  UNION ALL SELECT 'BGC_30TH_ST', '30th st bgc'
  UNION ALL SELECT 'BGC_31ST_ST', 'bgc 31st'
  UNION ALL SELECT 'BGC_31ST_ST', '31st st bgc'
  UNION ALL SELECT 'BGC_34TH_ST', 'bgc 34th'
  UNION ALL SELECT 'BGC_34TH_ST', '34th st bgc'
  UNION ALL SELECT 'BGC_5TH_AVE_HUB', 'bgc 5th junction'
  UNION ALL SELECT 'BGC_5TH_AVE_HUB', '5th 30th bgc'
  UNION ALL SELECT 'BGC_ONE_NEO', 'one neo'
  UNION ALL SELECT 'BGC_ONE_NEO', 'net one bgc'
  UNION ALL SELECT 'BGC_ONE_NEO', '1 neo bgc'
  UNION ALL SELECT 'BGC_TWO_NEO', 'two neo'
  UNION ALL SELECT 'BGC_TWO_NEO', 'net square bgc'
  UNION ALL SELECT 'BGC_TWO_NEO', '2 neo bgc'
  UNION ALL SELECT 'BGC_THREE_NEO', 'three neo'
  UNION ALL SELECT 'BGC_THREE_NEO', 'net quad bgc'
  UNION ALL SELECT 'BGC_THREE_NEO', '3 neo bgc'
  UNION ALL SELECT 'BGC_FOUR_NEO', 'four neo'
  UNION ALL SELECT 'BGC_FOUR_NEO', 'net plaza bgc'
  UNION ALL SELECT 'BGC_FOUR_NEO', '4 neo bgc'
  UNION ALL SELECT 'BGC_FIVE_NEO', 'five neo'
  UNION ALL SELECT 'BGC_FIVE_NEO', 'net cube bgc'
  UNION ALL SELECT 'BGC_FIVE_NEO', '5 neo bgc'
  UNION ALL SELECT 'BGC_SIX_NEO', 'six neo'
  UNION ALL SELECT 'BGC_SIX_NEO', 'net lima bgc'
  UNION ALL SELECT 'BGC_SIX_NEO', '6 neo bgc'
  UNION ALL SELECT 'BGC_SEVEN_NEO', 'seven neo'
  UNION ALL SELECT 'BGC_SEVEN_NEO', 'net park bgc'
  UNION ALL SELECT 'BGC_SEVEN_NEO', '7 neo bgc'
  UNION ALL SELECT 'BGC_NET_PARK', 'net lima bgc towers'
  UNION ALL SELECT 'BGC_NET_PARK', 'net lima towers'
  UNION ALL SELECT 'BGC_FINANCE_CTR', 'finance centre bgc'
  UNION ALL SELECT 'BGC_FINANCE_CTR', 'the finance bgc'
  UNION ALL SELECT 'BGC_METROBANK_CTR', 'metrobank bgc'
  UNION ALL SELECT 'BGC_METROBANK_CTR', 'metrobank center bgc'
  UNION ALL SELECT 'BGC_W_CITY_CTR', 'w city bgc'
  UNION ALL SELECT 'BGC_W_CITY_CTR', 'w city center bgc'
  UNION ALL SELECT 'BGC_W_5TH_AVE', 'w fifth bgc'
  UNION ALL SELECT 'BGC_W_5TH_AVE', 'w 5th bgc'
  UNION ALL SELECT 'BGC_ARTHALAND', 'arthaland bgc'
  UNION ALL SELECT 'BGC_ARTHALAND', 'century pacific tower'
  UNION ALL SELECT 'BGC_PSE_TOWER', 'pse bgc'
  UNION ALL SELECT 'BGC_PSE_TOWER', 'pse tower bgc'
  UNION ALL SELECT 'BGC_PSE_TOWER', 'stock exchange bgc'
  UNION ALL SELECT 'BGC_MENARCO', 'menarco bgc'
  UNION ALL SELECT 'BGC_MENARCO', 'menarco tower bgc'
  UNION ALL SELECT 'BGC_ONE_WORLD', 'one world bgc'
  UNION ALL SELECT 'BGC_ONE_WORLD', 'one world place bgc'
  UNION ALL SELECT 'BGC_ECOTOWER', 'ecotower bgc'
  UNION ALL SELECT 'BGC_ORE_CENTRAL', 'ore central bgc'
  UNION ALL SELECT 'BGC_ORE_CENTRAL', 'ore bgc'
  UNION ALL SELECT 'BGC_CORP_CTR', 'bgc corporate'
  UNION ALL SELECT 'BGC_CORP_CTR', 'bgc corp center'
  UNION ALL SELECT 'BGC_ST_LUKES', 'st lukes bgc hospital'
  UNION ALL SELECT 'BGC_ST_LUKES', 'slmc bgc hospital'
  UNION ALL SELECT 'BGC_GLOBE_TOWER', 'globe tower bgc'
  UNION ALL SELECT 'BGC_GLOBE_TOWER', 'globe bgc'
  UNION ALL SELECT 'BGC_JP_MORGAN', 'jp morgan bgc'
  UNION ALL SELECT 'BGC_JP_MORGAN', 'jpmorgan bgc'
  UNION ALL SELECT 'BGC_JP_MORGAN', 'j.p. morgan bgc'
  UNION ALL SELECT 'BGC_GOOGLE_PH', 'google bgc'
  UNION ALL SELECT 'BGC_GOOGLE_PH', 'google philippines bgc'
  UNION ALL SELECT 'BGC_SERENDRA', 'serendra one'
  UNION ALL SELECT 'BGC_SERENDRA', 'serendra two'
  UNION ALL SELECT 'BGC_SERENDRA', 'serendra bgc bonifacio'
  UNION ALL SELECT 'BGC_PACIFIC_PLAZA', 'pacific plaza bgc'
  UNION ALL SELECT 'BGC_PACIFIC_PLAZA', 'pacific plaza towers bgc'
  UNION ALL SELECT 'BGC_ARYA', 'arya bgc'
  UNION ALL SELECT 'BGC_ARYA', 'arya residences bgc'
  UNION ALL SELECT 'BGC_ONE_MCKINLEY', 'one mckinley bgc'
  UNION ALL SELECT 'BGC_FORBESWOOD', 'forbeswood bgc'
  UNION ALL SELECT 'BGC_FORBESWOOD', 'forbeswood heights'
  UNION ALL SELECT 'BGC_TRION', 'trion bgc'
  UNION ALL SELECT 'BGC_TRION', 'trion towers bgc'
  UNION ALL SELECT 'BGC_UPTOWN_RITZ', 'uptown ritz bgc'
  UNION ALL SELECT 'BGC_UPTOWN_RITZ', 'ritz bgc'
  UNION ALL SELECT 'BGC_AVIDA_TURF', 'avida turf bgc'
  UNION ALL SELECT 'BGC_AVIDA_TURF', 'avida bgc'
  UNION ALL SELECT 'BGC_MARIDIEN', 'maridien bgc'
  UNION ALL SELECT 'BGC_VERVE', 'verve bgc'
  UNION ALL SELECT 'BGC_VERVE', 'verve residences bgc'
  UNION ALL SELECT 'BGC_ONE_MARIDIEN', 'one maridien bgc'
  UNION ALL SELECT 'BGC_ONE_MARIDIEN', 'high street south bgc'
  UNION ALL SELECT 'BGC_SERENDRA_PIAZZA', 'serendra piazza bgc'
  UNION ALL SELECT 'BGC_AVIDA_CITYFLEX', 'cityflex bgc'
  UNION ALL SELECT 'BGC_AVIDA_CITYFLEX', 'avida cityflex bgc'
  UNION ALL SELECT 'BGC_VERITERE', 'veritere bgc'
  UNION ALL SELECT 'BGC_VERITERE', 'avida 34th bgc'
  UNION ALL SELECT 'BGC_LANDER_BGC', 'landers bgc'
  UNION ALL SELECT 'BGC_LANDER_BGC', 'landers superstore bgc'
  UNION ALL SELECT 'BGC_SHANGRI_LA', 'shangri la fort'
  UNION ALL SELECT 'BGC_SHANGRI_LA', 'shangri-la bgc'
  UNION ALL SELECT 'BGC_SHANGRI_LA', 'shangri la bgc'
  UNION ALL SELECT 'BGC_SHANGRI_LA', 'slatf'
  UNION ALL SELECT 'BGC_GRAND_HYATT', 'grand hyatt bgc hotel'
  UNION ALL SELECT 'BGC_GRAND_HYATT', 'hyatt bgc hotel'
  UNION ALL SELECT 'BGC_ASCOTT_BGC', 'ascott bgc'
  UNION ALL SELECT 'BGC_ASCOTT_BGC', 'ascott bonifacio'
  UNION ALL SELECT 'BGC_SEDA_BGC', 'seda bonifacio'
  UNION ALL SELECT 'BGC_SEDA_BGC', 'seda hotel bgc'
  UNION ALL SELECT 'BGC_F1_HOTEL', 'f1 hotel bgc'
  UNION ALL SELECT 'BGC_BURGOS_CIRCLE', 'burgos circle bgc'
  UNION ALL SELECT 'BGC_BURGOS_CIRCLE', 'forbes town bgc'
  UNION ALL SELECT 'BGC_MITSUKOSHI', 'mitsukoshi bgc mall'
  UNION ALL SELECT 'BGC_MITSUKOSHI', 'mitsukoshi mall bgc'
  UNION ALL SELECT 'BGC_CENTRAL_SQUARE', 'central square bgc'
  UNION ALL SELECT 'BGC_CENTRAL_SQUARE', 'central sq bgc'
  UNION ALL SELECT 'BGC_MIND_MUSEUM', 'mind museum bgc'
  UNION ALL SELECT 'BGC_MIND_MUSEUM', 'jy campos park bgc'
  UNION ALL SELECT 'BGC_UPTOWN_PARADE', 'uptown parade bgc'
  UNION ALL SELECT 'BGC_UPTOWN_PARADE', 'uptown bgc parade'
  UNION ALL SELECT 'BGC_UPTOWN_TOWERS', 'uptown towers bgc'
  UNION ALL SELECT 'BGC_PARK_TRIANGLE', 'park triangle bgc'
  UNION ALL SELECT 'BGC_PARK_TRIANGLE', 'park tri bgc'
  UNION ALL SELECT 'BGC_GRAND_HYATT_GATE', 'grand hyatt residences bgc'
  UNION ALL SELECT 'BGC_TURF_BGC', 'turf bgc 9th'
  UNION ALL SELECT 'BGC_TURF_BGC', 'bgc 9th turf'
  UNION ALL SELECT 'BGC_S_AND_R_BGC', 's&r bgc'
  UNION ALL SELECT 'BGC_S_AND_R_BGC', 'sandi r bgc'
  UNION ALL SELECT 'BGC_VERITOWN_NORTH', 'veritown bgc'
  UNION ALL SELECT 'BGC_KALAYAAN_BRIDGE', 'bgc ortigas bridge'
  UNION ALL SELECT 'BGC_KALAYAAN_BRIDGE', 'kalayaan bridge bgc'
  UNION ALL SELECT 'BGC_MARKET_MARKET_PUV', 'market market puv'
  UNION ALL SELECT 'BGC_MARKET_MARKET_PUV', 'mm puv bgc'
  UNION ALL SELECT 'BGC_MARKET_MARKET_PUV', 'puv bgc terminal'
  UNION ALL SELECT 'BGC_MCKINLEY_PARKWAY', 'mckinley parkway bgc'
  UNION ALL SELECT 'BGC_MCKINLEY_PARKWAY', 'aura exit bgc'
  UNION ALL SELECT 'BGC_SM_AURA_OFFICE', 'sm aura office bgc'
  UNION ALL SELECT 'BGC_SM_AURA_OFFICE', 'aura office bgc'
  UNION ALL SELECT 'BGC_MCKINLEY_EXCHANGE', 'mckinley exchange bgc'
  UNION ALL SELECT 'BGC_C5_ELEVATED_EXIT', 'bgc c5 exit'
  UNION ALL SELECT 'BGC_C5_ELEVATED_EXIT', 'c5 bgc elevated'
  UNION ALL SELECT 'BGC_32ND_ST_FLYOVER', '32nd st flyover bgc'
  UNION ALL SELECT 'BGC_32ND_ST_FLYOVER', '32nd flyover bgc'
  UNION ALL SELECT 'BGC_NORTH_GATE_ENTRY', 'bgc north gate'
  UNION ALL SELECT 'BGC_NORTH_GATE_ENTRY', 'north gate bgc'
  UNION ALL SELECT 'BGC_LAWTON_5TH_AVE', 'lawton bgc'
  UNION ALL SELECT 'BGC_LAWTON_5TH_AVE', 'lawton 5th bgc'
  UNION ALL SELECT 'BGC_LAWTON_5TH_AVE', 'lawton avenue bgc'
  UNION ALL SELECT 'BGC_KALAYAAN_GATEWAY', 'kalayaan bgc'
  UNION ALL SELECT 'BGC_KALAYAAN_GATEWAY', 'bgc kalayaan entry'
  UNION ALL SELECT 'BGC_ESSENSA', 'essensa bgc'
  UNION ALL SELECT 'BGC_ESSENSA', 'east forbes bgc'
  UNION ALL SELECT 'BGC_INFANTRY_RD', 'infantry road bgc'
  UNION ALL SELECT 'BGC_INFANTRY_RD', 'bayani road bgc'
  UNION ALL SELECT 'BGC_BUTITI_ST', 'butiti bgc'
  UNION ALL SELECT 'BGC_BUTITI_ST', 'park triangle area bgc'
  UNION ALL SELECT 'BGC_CYBER_SIGMA', 'cyber sigma bgc'
  UNION ALL SELECT 'BGC_STI_ACADEMIC', 'sti bgc'
  UNION ALL SELECT 'BGC_STI_ACADEMIC', 'sti academic bgc'
  UNION ALL SELECT 'BGC_UNIVERSITY_PARK', 'university park bgc'
  UNION ALL SELECT 'BGC_UNIVERSITY_PARK', 'ism bgc'
  UNION ALL SELECT 'BGC_UNIVERSITY_PARK', 'bsm bgc'
  UNION ALL SELECT 'MKH_VENICE_GRAND_CANAL', 'venice mckinley hill'
  UNION ALL SELECT 'MKH_VENICE_GRAND_CANAL', 'grand canal mckinley'
  UNION ALL SELECT 'MKH_UPPER_MCKINLEY', 'upper mckinley'
  UNION ALL SELECT 'MKH_UPPER_MCKINLEY', 'upper mckinley hill'
  UNION ALL SELECT 'MKH_UPPER_MCKINLEY', 'upper mckinley road'
  UNION ALL SELECT 'MKH_SCIENCE_HUB', 'science hub mckinley'
  UNION ALL SELECT 'MKH_SCIENCE_HUB', 'mckinley science hub'
  UNION ALL SELECT 'MKH_COMMERCE_SITE', 'commerce industry plaza mckinley'
  UNION ALL SELECT 'MKH_MORGAN_SUITES', 'morgan suites mckinley'
  UNION ALL SELECT 'TGG_ARCA_SOUTH_MAIN', 'arca south taguig main'
  UNION ALL SELECT 'TGG_ARCA_SOUTH_MAIN', 'arca south transit'
  UNION ALL SELECT 'TGG_ONE_ARCA_SOUTH', 'one arca south'
  UNION ALL SELECT 'TGG_ONE_ARCA_SOUTH', 'arca south corporate'
  UNION ALL SELECT 'TGG_SAVYA_FINANCIAL', 'savya arca south'
  UNION ALL SELECT 'TGG_SAVYA_FINANCIAL', 'savya financial'
  UNION ALL SELECT 'TGG_FTI_RECI_RD', 'fti reciprocity'
  UNION ALL SELECT 'TGG_FTI_RECI_RD', 'reciprocity road bicutan'
  UNION ALL SELECT 'TGG_FTI_RECI_RD', 'fti lower bicutan'
  UNION ALL SELECT 'TGG_LOWER_BICUTAN_HALL', 'lower bicutan brgy'
  UNION ALL SELECT 'TGG_LOWER_BICUTAN_HALL', 'brgy lower bicutan'
  UNION ALL SELECT 'TGG_CAYETANO_BLVD_C5', 'cayetano blvd'
  UNION ALL SELECT 'TGG_CAYETANO_BLVD_C5', 'cayetano c5'
  UNION ALL SELECT 'TGG_CAYETANO_BLVD_C5', 'levi mariano c5'
  UNION ALL SELECT 'TGG_TENEMENT_TAGUIG', 'taguig tenement'
  UNION ALL SELECT 'TGG_TENEMENT_TAGUIG', 'western bicutan tenement'
  UNION ALL SELECT 'TGG_LEVI_MARIANO_HUB', 'levi mariano taguig'
  UNION ALL SELECT 'TGG_LEVI_MARIANO_HUB', 'levi mariano ave'
  UNION ALL SELECT 'TGG_GRACE_RESIDENCES', 'grace residences taguig'
  UNION ALL SELECT 'TGG_VISTA_MALL_TAGUIG', 'vista mall taguig'
  UNION ALL SELECT 'TGG_VISTA_MALL_TAGUIG', 'camella colina taguig'
  UNION ALL SELECT 'TGG_ACACIA_ESTATES', 'acacia estates taguig'
  UNION ALL SELECT 'TGG_ACACIA_ESTATES', 'acacia taguig'
  UNION ALL SELECT 'TGG_PINAGSAMA_VILLAGE', 'pinagsama taguig'
  UNION ALL SELECT 'TGG_PINAGSAMA_VILLAGE', 'pinagsama village'
  UNION ALL SELECT 'TGG_BCDA_VILLAGE', 'bcda taguig'
  UNION ALL SELECT 'TGG_BCDA_VILLAGE', 'bcda village taguig'
  UNION ALL SELECT 'TGG_C6_LAKESHORE_HUB', 'c6 taguig'
  UNION ALL SELECT 'TGG_C6_LAKESHORE_HUB', 'lakeshore taguig'
  UNION ALL SELECT 'TGG_C6_LAKESHORE_HUB', 'hagonoy c6'
  UNION ALL SELECT 'TGG_LAKESHORE_HALL', 'lakeshore hall taguig'
  UNION ALL SELECT 'TGG_C6_TAGUIG_EXIT', 'c6 exit taguig'
  UNION ALL SELECT 'TGG_C6_TAGUIG_EXIT', 'napindan c6'
  UNION ALL SELECT 'TGG_NAPINDAN_BRIDGE', 'napindan bridge'
  UNION ALL SELECT 'TGG_NAPINDAN_BRIDGE', 'pasig napindan boundary'
  UNION ALL SELECT 'TGG_TIPAS_CENTRAL', 'tipas taguig'
  UNION ALL SELECT 'TGG_TIPAS_CENTRAL', 'brgy tipas'
  UNION ALL SELECT 'TGG_BAMBANG_CHURCH', 'bambang taguig'
  UNION ALL SELECT 'TGG_BAMBANG_CHURCH', 'brgy bambang taguig'
  UNION ALL SELECT 'TGG_SAN_ANA_POBLACION', 'sta ana taguig'
  UNION ALL SELECT 'TGG_SAN_ANA_POBLACION', 'taguig city university'
  UNION ALL SELECT 'TGG_LAWTON_GATE_3', 'lawton gate 3'
  UNION ALL SELECT 'TGG_LAWTON_GATE_3', 'gate 3 nichols'
  UNION ALL SELECT 'TGG_LAWTON_GATE_3', 'nichols bgc'
  UNION ALL SELECT 'TGG_LAWTON_GATE_5', 'lawton gate 5'
  UNION ALL SELECT 'TGG_LAWTON_GATE_5', 'cypress bgc'
  UNION ALL SELECT 'TGG_LAWTON_GATE_5', 'bgc gate 5'
  UNION ALL SELECT 'TGG_BAYANI_ROAD_AFPOVAI', 'afpovai'
  UNION ALL SELECT 'TGG_BAYANI_ROAD_AFPOVAI', 'bayani road gate 1'
  UNION ALL SELECT 'TGG_BAYANI_ROAD_AFPOVAI', 'afpovai gate'
  UNION ALL SELECT 'TGG_HERITAGE_PARK_G', 'heritage park taguig'
  UNION ALL SELECT 'TGG_COMMAND_GENERAL', 'cgsc taguig'
  UNION ALL SELECT 'TGG_COMMAND_GENERAL', 'command staff college taguig'
  UNION ALL SELECT 'TGG_PHIL_ARMY_OFFICERS', 'phil army officers'
  UNION ALL SELECT 'TGG_PHIL_ARMY_OFFICERS', 'army officers village taguig'
  UNION ALL SELECT 'TGG_BICUTAN_PNR_HUB', 'bicutan pnr'
  UNION ALL SELECT 'TGG_BICUTAN_PNR_HUB', 'sm bicutan terminal'
  UNION ALL SELECT 'TGG_BICUTAN_PNR_HUB', 'sm bicutan'
  UNION ALL SELECT 'TGG_ML_QUEZON_SOUTH', 'ml quezon taguig'
  UNION ALL SELECT 'TGG_ML_QUEZON_SOUTH', 'm.l. quezon taguig'
  UNION ALL SELECT 'TGG_WEST_BICUTAN_WSR', 'west bicutan wsr'
  UNION ALL SELECT 'TGG_WEST_BICUTAN_WSR', 'wsr west bicutan'
  UNION ALL SELECT 'TGG_MCKINLEY_HILL_GATE', 'mckinley hill lawton gate'
  UNION ALL SELECT 'TGG_BGC_SOUTH_GATEWAY', 'bgc south gate'
  UNION ALL SELECT 'TGG_BGC_SOUTH_GATEWAY', 'mckinley south bgc'
  UNION ALL SELECT 'MKT_AYALA_AVE', 'ayala ave'
  UNION ALL SELECT 'MKT_AYALA_AVE', 'ayala avenue makati'
  UNION ALL SELECT 'MKT_AYALA_AVE', 'ayala road makati'
  UNION ALL SELECT 'MKT_GIL_PUYAT', 'buendia makati'
  UNION ALL SELECT 'MKT_GIL_PUYAT', 'gil puyat'
  UNION ALL SELECT 'MKT_GIL_PUYAT', 'gil puyat avenue'
  UNION ALL SELECT 'MKT_GIL_PUYAT', 'buendia ave'
  UNION ALL SELECT 'MKT_MAKATI_AVE', 'makati ave'
  UNION ALL SELECT 'MKT_MAKATI_AVE', 'makati avenue makati'
  UNION ALL SELECT 'MKT_CHINO_ROCES', 'pasong tamo'
  UNION ALL SELECT 'MKT_CHINO_ROCES', 'chino roces'
  UNION ALL SELECT 'MKT_CHINO_ROCES', 'pasong tamo makati'
  UNION ALL SELECT 'MKT_PASEO_ROXAS', 'paseo roxas'
  UNION ALL SELECT 'MKT_PASEO_ROXAS', 'paseo de roxas makati'
  UNION ALL SELECT 'MKT_ARNAIZ_AVE', 'arnaiz avenue makati'
  UNION ALL SELECT 'MKT_ARNAIZ_AVE', 'pasay road makati'
  UNION ALL SELECT 'MKT_AMORSOLO', 'amorsolo makati'
  UNION ALL SELECT 'MKT_AMORSOLO', 'amorsolo st makati'
  UNION ALL SELECT 'MKT_JP_RIZAL', 'jp rizal makati'
  UNION ALL SELECT 'MKT_JP_RIZAL', 'jp rizal avenue makati'
  UNION ALL SELECT 'MKT_KALAYAAN', 'kalayaan makati'
  UNION ALL SELECT 'MKT_KALAYAAN', 'kalayaan ave makati'
  UNION ALL SELECT 'MKT_ESTRELLA', 'estrella makati'
  UNION ALL SELECT 'MKT_ESTRELLA', 'estrella st makati'
  UNION ALL SELECT 'MKT_JUPITER', 'jupiter makati'
  UNION ALL SELECT 'MKT_JUPITER', 'jupiter st makati'
  UNION ALL SELECT 'MKT_PBCOM_TOWER', 'pbcom makati'
  UNION ALL SELECT 'MKT_PBCOM_TOWER', 'pbcom tower makati'
  UNION ALL SELECT 'MKT_GT_TOWER', 'gt tower makati'
  UNION ALL SELECT 'MKT_GT_TOWER', 'gt international makati'
  UNION ALL SELECT 'MKT_RCBC_PLAZA', 'rcbc makati'
  UNION ALL SELECT 'MKT_RCBC_PLAZA', 'yuchengco tower'
  UNION ALL SELECT 'MKT_RCBC_PLAZA', 'rcbc plaza makati'
  UNION ALL SELECT 'MKT_AYALA_TOWER_ONE', 'ayala tower one makati'
  UNION ALL SELECT 'MKT_AYALA_TOWER_ONE', 'ayala tower makati'
  UNION ALL SELECT 'MKT_ZUellig_Bldg', 'zuellig makati'
  UNION ALL SELECT 'MKT_ZUellig_Bldg', 'zuellig building makati'
  UNION ALL SELECT 'MKT_LKG_TOWER', 'lkg makati'
  UNION ALL SELECT 'MKT_LKG_TOWER', 'lkg tower makati'
  UNION ALL SELECT 'MKT_ENTERPRISE_CTR', 'enterprise center makati'
  UNION ALL SELECT 'MKT_ENTERPRISE_CTR', 'enterprise makati'
  UNION ALL SELECT 'MKT_PACIFIC_STAR', 'pacific star makati'
  UNION ALL SELECT 'MKT_AYALA_NORTH_EXCH', 'ayala north exchange makati'
  UNION ALL SELECT 'MKT_AYALA_NORTH_EXCH', 'ane makati'
  UNION ALL SELECT 'MKT_6789_AYALA', '6789 ayala makati'
  UNION ALL SELECT 'MKT_INSULAR_LIFE', 'insular life makati'
  UNION ALL SELECT 'MKT_SALCEDO_VILL_PARK', 'salcedo park makati'
  UNION ALL SELECT 'MKT_SALCEDO_VILL_PARK', 'velazquez park'
  UNION ALL SELECT 'MKT_LEGAZPI_VILL_PARK', 'legazpi park makati'
  UNION ALL SELECT 'MKT_LEGAZPI_VILL_PARK', 'washington sycip park'
  UNION ALL SELECT 'MKT_VALERO_ST_HUB', 'valero makati'
  UNION ALL SELECT 'MKT_VALERO_ST_HUB', 'valero street makati'
  UNION ALL SELECT 'MKT_KALAYAAN_AVE_HUB', 'kalayaan makati ave junction'
  UNION ALL SELECT 'MKT_JP_RIZAL_PIVOT', 'jp rizal pivot makati'
  UNION ALL SELECT 'MKT_H_V_DELA_COSTA', 'hv dela costa makati'
  UNION ALL SELECT 'MKT_H_V_DELA_COSTA', 'leviste makati'
  UNION ALL SELECT 'MKT_AMORSOLO_CREEK_SIDE', 'amorsolo creek makati'
  UNION ALL SELECT 'MKT_AMORSOLO_CREEK_SIDE', 'mile long makati'
  UNION ALL SELECT 'MKT_TORDESILLAS_SALCEDO', 'tordesillas salcedo makati'
  UNION ALL SELECT 'MKT_TORDESILLAS_SALCEDO', 'bautista salcedo makati'
  UNION ALL SELECT 'MKT_VALERO_ACCESS_RD', 'valero access makati'
  UNION ALL SELECT 'MKT_VALERO_ACCESS_RD', 'valero loading zone'
  UNION ALL SELECT 'MKT_LEGASPI_ACTIVE_PARK', 'legaspi active park'
  UNION ALL SELECT 'MKT_LEGASPI_ACTIVE_PARK', 'rada st makati'
  UNION ALL SELECT 'MKT_DELA_ROSA_BRIDGE', 'dela rosa walkway makati'
  UNION ALL SELECT 'MKT_DELA_ROSA_BRIDGE', 'dela rosa bridge makati'
  UNION ALL SELECT 'MKT_DELA_ROSA_STOP', 'dela rosa stop makati'
  UNION ALL SELECT 'MKT_DELA_ROSA_STOP', 'dela rosa makati loading'
  UNION ALL SELECT 'MKT_VALERO_STRAT_HUB', 'stratford makati'
  UNION ALL SELECT 'MKT_VALERO_STRAT_HUB', 'valero stratford makati'
  UNION ALL SELECT 'MKT_POWER_PLANT', 'power plant rockwell'
  UNION ALL SELECT 'MKT_POWER_PLANT', 'power plant makati'
  UNION ALL SELECT 'MKT_POWER_PLANT', 'ppm'
  UNION ALL SELECT 'MKT_ONE_ROCKWELL', 'one rockwell makati'
  UNION ALL SELECT 'MKT_ONE_ROCKWELL', '1 rockwell'
  UNION ALL SELECT 'MKT_PROSCENIUM', 'proscenium makati'
  UNION ALL SELECT 'MKT_PROSCENIUM', 'proscenium rockwell'
  UNION ALL SELECT 'MKT_PH_SEA_CTR', 'phinma rockwell'
  UNION ALL SELECT 'MKT_PH_SEA_CTR', 'rockwell hub phinma'
  UNION ALL SELECT 'MKT_CENTURY_CITY', 'century city mall makati'
  UNION ALL SELECT 'MKT_CENTURY_CITY', 'trump tower makati'
  UNION ALL SELECT 'MKT_CIRCUIT_MAKATI', 'circuit ayala'
  UNION ALL SELECT 'MKT_CIRCUIT_MAKATI', 'circuit ayala mall'
  UNION ALL SELECT 'MKT_P_BURGOS', 'p burgos makati'
  UNION ALL SELECT 'MKT_P_BURGOS', 'burgos makati'
  UNION ALL SELECT 'MKT_P_BURGOS', 'poblacion burgos'
  UNION ALL SELECT 'MKT_ROCKWELL_CENTER', 'rockwell center makati'
  UNION ALL SELECT 'MKT_ROCKWELL_CENTER', 'power plant mall makati'
  UNION ALL SELECT 'MKT_POBLACION_MARKET', 'poblacion makati market'
  UNION ALL SELECT 'MKT_POBLACION_MARKET', 'poblacion palengke'
  UNION ALL SELECT 'MKT_POBLACION_CENTRAL', 'poblacion makati central'
  UNION ALL SELECT 'MKT_POBLACION_CENTRAL', 'a venue makati'
  UNION ALL SELECT 'MKT_A_MABINI_POBLACION', 'a mabini makati'
  UNION ALL SELECT 'MKT_A_MABINI_POBLACION', 'mabini poblacion'
  UNION ALL SELECT 'MKT_CIRCUIT_MAKATI_DROP', 'circuit riverfront makati'
  UNION ALL SELECT 'MKT_CIRCUIT_POWER_STATION', 'circuit s&r makati'
  UNION ALL SELECT 'MKT_CIRCUIT_POWER_STATION', 'circuit powerhouse makati'
  UNION ALL SELECT 'MKT_ONE_AYALA', 'one ayala makati hub'
  UNION ALL SELECT 'MKT_ONE_AYALA', '1 ayala terminal makati'
  UNION ALL SELECT 'MKT_GLORIETTA', 'glorietta 1 makati'
  UNION ALL SELECT 'MKT_GLORIETTA', 'glorietta 2 makati'
  UNION ALL SELECT 'MKT_GLORIETTA', 'glorietta 3 makati'
  UNION ALL SELECT 'MKT_GLORIETTA', 'glorietta 4 makati'
  UNION ALL SELECT 'MKT_GLORIETTA', 'glorietta 5 makati'
  UNION ALL SELECT 'MKT_GREENBELT', 'greenbelt 1 makati'
  UNION ALL SELECT 'MKT_GREENBELT', 'greenbelt 2 makati'
  UNION ALL SELECT 'MKT_GREENBELT', 'greenbelt 3 makati'
  UNION ALL SELECT 'MKT_GREENBELT', 'greenbelt 5 makati'
  UNION ALL SELECT 'MKT_SM_MAKATI', 'sm makati'
  UNION ALL SELECT 'MKT_SM_MAKATI', 'sm city makati'
  UNION ALL SELECT 'MKT_LANDMARK_MKT', 'landmark mall makati'
  UNION ALL SELECT 'MKT_SHANGRI_LA_MKT', 'shangri la makati'
  UNION ALL SELECT 'MKT_SHANGRI_LA_MKT', 'shangri-la makati'
  UNION ALL SELECT 'MKT_PENINSULA_PH', 'peninsula manila'
  UNION ALL SELECT 'MKT_PENINSULA_PH', 'peninsula hotel makati'
  UNION ALL SELECT 'MKT_FAIRMONT_RAFFLES', 'fairmont makati'
  UNION ALL SELECT 'MKT_FAIRMONT_RAFFLES', 'raffles makati'
  UNION ALL SELECT 'MKT_AYALA_TRIANGLE', 'ayala triangle makati'
  UNION ALL SELECT 'MKT_AYALA_TRIANGLE', 'triangle gardens makati'
  UNION ALL SELECT 'MKT_WALK_WAY', 'dela rosa makati'
  UNION ALL SELECT 'MKT_WALK_WAY', 'dela rosa entrance makati'
  UNION ALL SELECT 'MKT_GREENBELT_1_DRIVE', 'greenbelt paseo makati'
  UNION ALL SELECT 'MKT_MAGALLANES_HUB', 'magallanes village slex'
  UNION ALL SELECT 'MKT_MAGALLANES_HUB', 'magallanes slex exit'
  UNION ALL SELECT 'MKT_MAGALLANES_VILLAGE', 'magallanes village makati'
  UNION ALL SELECT 'MKT_MAGALLANES_VILLAGE', 'magallanes gate'
  UNION ALL SELECT 'MKT_DASMARINAS_GATE', 'dasmarinas gate makati'
  UNION ALL SELECT 'MKT_DASMARINAS_GATE', 'dasma arnaiz gate'
  UNION ALL SELECT 'MKT_DASMARINAS_VILL_G', 'dasmarinas pasay road gate'
  UNION ALL SELECT 'MKT_DASMARINAS_VILL_G', 'dasma pasay road makati'
  UNION ALL SELECT 'MKT_FORBES_PARK_GATE', 'forbes park makati'
  UNION ALL SELECT 'MKT_FORBES_PARK_GATE', 'forbes gate mckinley'
  UNION ALL SELECT 'MKT_SAN_LORENZO_GATE', 'san lorenzo gate makati'
  UNION ALL SELECT 'MKT_URDANETA_VILL_GATE', 'urdaneta village makati'
  UNION ALL SELECT 'MKT_URDANETA_VILL_GATE', 'urdaneta gate'
  UNION ALL SELECT 'MKT_ALPHALAND_SOUTH', 'alphaland southgate'
  UNION ALL SELECT 'MKT_ALPHALAND_SOUTH', 'alphaland edsa makati'
  UNION ALL SELECT 'MKT_ALPHALAND_SLEX', 'alphaland slex makati'
  UNION ALL SELECT 'MKT_MAGALLANES_MRT_HUB', 'magallanes mrt makati'
  UNION ALL SELECT 'MKT_MAGALLANES_MRT_HUB', 'mrt magallanes loading'
  UNION ALL SELECT 'MKT_EDSA_MAGALLANES_TERM', 'magallanes interchange slex'
  UNION ALL SELECT 'MKT_EDSA_MAGALLANES_TERM', 'magallanes edsa slex'
  UNION ALL SELECT 'MKT_BUENDIA_SLEX', 'buendia slex makati'
  UNION ALL SELECT 'MKT_BUENDIA_SLEX', 'gil puyat slex'
  UNION ALL SELECT 'MKT_CHINO_ROCES_EXT', 'chino roces ext'
  UNION ALL SELECT 'MKT_CHINO_ROCES_EXT', 'kayamanan makati'
  UNION ALL SELECT 'MKT_CHINO_ROCES_SOUTH', 'chino roces mantrade'
  UNION ALL SELECT 'MKT_CHINO_ROCES_SOUTH', 'chino roces slex'
  UNION ALL SELECT 'MKT_CHINO_ROCES_PRC', 'chino roces prc'
  UNION ALL SELECT 'MKT_CHINO_ROCES_PRC', 'prc makati'
  UNION ALL SELECT 'MKT_CHINO_ROCES_PRC', 'prc chino roces'
  UNION ALL SELECT 'MKT_PASONG_TAMO_SHOPWISE', 'shopwise makati'
  UNION ALL SELECT 'MKT_PASONG_TAMO_SHOPWISE', 'pasong tamo shopwise'
  UNION ALL SELECT 'MKT_PASONG_TAMO_EXT', 'pasong tamo ext makati'
  UNION ALL SELECT 'MKT_PASONG_TAMO_EXT', 'ecoplaza makati'
  UNION ALL SELECT 'MKT_LA_FUERZA_HUB', 'la fuerza makati'
  UNION ALL SELECT 'MKT_LA_FUERZA_HUB', 'la fuerza plaza'
  UNION ALL SELECT 'MKT_OSMENA_HWY_HUB', 'osmena highway makati'
  UNION ALL SELECT 'MKT_OSMENA_HWY_HUB', 'san andres makati'
  UNION ALL SELECT 'MKT_GUADALUPE_FERRY', 'guadalupe ferry makati'
  UNION ALL SELECT 'MKT_GUADALUPE_FERRY', 'guadalupe riverfront'
  UNION ALL SELECT 'MKT_GUADALUPE_MKT_HUB', 'guadalupe complex makati'
  UNION ALL SELECT 'MKT_GUADALUPE_MKT_HUB', 'guadalupe commercial'
  UNION ALL SELECT 'MKT_GUADALUPE_VIEJO', 'guadalupe viejo makati'
  UNION ALL SELECT 'MKT_GUADALUPE_VIEJO', 'guadalupe edsa makati'
  UNION ALL SELECT 'MKT_ESTRELLA_EDSA_HUB', 'estrella edsa makati'
  UNION ALL SELECT 'MKT_ESTRELLA_EDSA_HUB', 'rockwell entry makati'
  UNION ALL SELECT 'MKT_ESTACION_ST', 'estacion makati'
  UNION ALL SELECT 'MKT_ESTACION_ST', 'pasay road pnr makati'
  UNION ALL SELECT 'MKT_CASH_AND_CARRY', 'cash and carry makati'
  UNION ALL SELECT 'MKT_CASH_AND_CARRY', 'filmore makati'
  UNION ALL SELECT 'MKT_ZOBEL_ROXAS_BOUNDARY', 'zobel roxas makati'
  UNION ALL SELECT 'MKT_ZOBEL_ROXAS_BOUNDARY', 'makati manila boundary'
  UNION ALL SELECT 'MKT_ZOBEL_ROXAS_NORTH', 'zobel roxas north makati'
  UNION ALL SELECT 'MKT_VITO_CRUZ_EXT_MKT', 'vito cruz makati'
  UNION ALL SELECT 'MKT_EVANGELISTA_ST_MKT', 'evangelista makati'
  UNION ALL SELECT 'MKT_EVANGELISTA_ST_MKT', 'bangkal makati'
  UNION ALL SELECT 'MKT_EVANGELISTA_MAIN', 'evangelista bangkal commercial'
  UNION ALL SELECT 'MKT_EVANGELISTA_MAIN', 'bangkal commercial makati'
  UNION ALL SELECT 'MKT_PIO_DEL_PILAR_HUB', 'pio pilar washington makati'
  UNION ALL SELECT 'MKT_PIO_DEL_PILAR_ZONE', 'pio del pilar arnaiz makati'
  UNION ALL SELECT 'MKT_TEJEROS_HUB', 'tejeros chino roces makati'
  UNION ALL SELECT 'MKT_TEJEROS_BOUNDARY', 'tejeros san andres makati'
  UNION ALL SELECT 'MKT_KALSADA_TEJEROS', 'kalsada tejeros makati'
  UNION ALL SELECT 'MKT_KALSADA_TEJEROS', 'prc tejeros makati'
  UNION ALL SELECT 'MKT_SAN_ISIDRO_HUB', 'san isidro buendia makati'
  UNION ALL SELECT 'MKT_SAN_ISIDRO_HUB', 'san isidro dian makati'
  UNION ALL SELECT 'MKT_STA_ANA_RACETRACK', 'sta ana makati'
  UNION ALL SELECT 'MKT_STA_ANA_RACETRACK', 'sta ana circuit makati'
  UNION ALL SELECT 'MKT_PEMBO_MARKET', 'pembo flower farm'
  UNION ALL SELECT 'MKT_PEMBO_MARKET', 'pembo market makati'
  UNION ALL SELECT 'MKT_PEMBO_FLOWER_FARM', 'pembo makati'
  UNION ALL SELECT 'MKT_PEMBO_FLOWER_FARM', 'flower farm makati'
  UNION ALL SELECT 'MKT_COMEMBO_HUB', 'comembo makati'
  UNION ALL SELECT 'MKT_COMEMBO_HUB', 'jp rizal ext makati'
  UNION ALL SELECT 'MKT_COMEMBO_MARKET', 'comembo market makati'
  UNION ALL SELECT 'MKT_COMEMBO_C5_RAMP', 'comembo c5 makati'
  UNION ALL SELECT 'MKT_REMB_CENTRAL', 'rembo makati'
  UNION ALL SELECT 'MKT_REMB_CENTRAL', 'rembo jp rizal'
  UNION ALL SELECT 'MKT_RIZAL_VILL_HUB', 'rizal village makati'
  UNION ALL SELECT 'MKT_JP_RIZAL_EXT_HUB', 'jp rizal ext makati west rembo'
  UNION ALL SELECT 'MKT_PITOGO_CENTRAL', 'pitogo makati'
  UNION ALL SELECT 'MKT_PITOGO_CENTRAL', 'bgc makati border pitogo'
  UNION ALL SELECT 'PSY_MOA_GLOBE', 'sm mall of asia pasay'
  UNION ALL SELECT 'PSY_MOA_GLOBE', 'moa globe'
  UNION ALL SELECT 'PSY_MOA_ARENA', 'moa arena pasay'
  UNION ALL SELECT 'PSY_SMX_CONVENTION', 'smx pasay'
  UNION ALL SELECT 'PSY_SMX_CONVENTION', 'smx convention pasay'
  UNION ALL SELECT 'PSY_ONE_ECOM', 'one ecom pasay'
  UNION ALL SELECT 'PSY_ONE_ECOM', '1 ecom pasay'
  UNION ALL SELECT 'PSY_ONE_ECOM', 'e-com pasay'
  UNION ALL SELECT 'PSY_TWO_ECOM', 'two ecom pasay'
  UNION ALL SELECT 'PSY_TWO_ECOM', '2 ecom pasay'
  UNION ALL SELECT 'PSY_FIVE_ECOM', 'five ecom pasay'
  UNION ALL SELECT 'PSY_FIVE_ECOM', '5 ecom pasay'
  UNION ALL SELECT 'PSY_CONRAD_MANILA', 'conrad hotel pasay'
  UNION ALL SELECT 'PSY_CONRAD_MANILA', 's maison pasay'
  UNION ALL SELECT 'PSY_IKEA_PASAY', 'ikea pasay'
  UNION ALL SELECT 'PSY_IKEA_PASAY', 'ikea ph pasay'
  UNION ALL SELECT 'PSY_SM_BY_THE_BAY', 'sm bay pasay'
  UNION ALL SELECT 'PSY_SM_BY_THE_BAY', 'sm by the bay pasay'
  UNION ALL SELECT 'PSY_MA_ROXAS_BLVD', 'roxas blvd pasay'
  UNION ALL SELECT 'PSY_MA_ROXAS_BLVD', 'macapagal roxas blvd'
  UNION ALL SELECT 'PSY_NEWPORT_WORLD', 'newport world pasay'
  UNION ALL SELECT 'PSY_NEWPORT_WORLD', 'resorts world pasay'
  UNION ALL SELECT 'PSY_NEWPORT_WORLD', 'rwm pasay'
  UNION ALL SELECT 'PSY_NEWPORT_MALL', 'newport mall pasay'
  UNION ALL SELECT 'PSY_MARRIOTT_MANILA', 'marriott pasay'
  UNION ALL SELECT 'PSY_MARRIOTT_MANILA', 'marriott hotel pasay'
  UNION ALL SELECT 'PSY_SAVOY_HOTEL', 'savoy pasay'
  UNION ALL SELECT 'PSY_SAVOY_HOTEL', 'savoy hotel pasay'
  UNION ALL SELECT 'PSY_BELMONT_HOTEL', 'belmont pasay'
  UNION ALL SELECT 'PSY_BELMONT_HOTEL', 'belmont hotel pasay'
  UNION ALL SELECT 'PSY_MRT_TAFT', 'taft mrt pasay'
  UNION ALL SELECT 'PSY_MRT_TAFT', 'mrt taft pasay'
  UNION ALL SELECT 'PSY_MRT_TAFT', 'taft avenue mrt'
  UNION ALL SELECT 'PSY_LRT_EDSA', 'lrt edsa pasay'
  UNION ALL SELECT 'PSY_LRT_EDSA', 'edsa lrt pasay'
  UNION ALL SELECT 'PSY_VICTORY_LINER', 'victory liner pasay terminal'
  UNION ALL SELECT 'PSY_VICTORY_LINER', 'victory liner bus'
  UNION ALL SELECT 'PSY_PHILTRANCO', 'philtranco bus pasay'
  UNION ALL SELECT 'PSY_PHILTRANCO', 'philtranco terminal'
  UNION ALL SELECT 'PSY_FIVE_STAR_BUS', 'five star bus pasay'
  UNION ALL SELECT 'PSY_FIVE_STAR_BUS', '5 star bus pasay'
  UNION ALL SELECT 'PSY_DLTB_TERMINAL', 'dltb pasay'
  UNION ALL SELECT 'PSY_DLTB_TERMINAL', 'dltb bus pasay'
  UNION ALL SELECT 'PSY_GEN_RODRIGO', 'tramo pasay'
  UNION ALL SELECT 'PSY_GEN_RODRIGO', 'gen rodrigo pasay'
  UNION ALL SELECT 'PSY_CCP_MAIN', 'ccp pasay'
  UNION ALL SELECT 'PSY_CCP_MAIN', 'cultural center pasay'
  UNION ALL SELECT 'PSY_PICC', 'picc pasay'
  UNION ALL SELECT 'PSY_PICC', 'convention center pasay'
  UNION ALL SELECT 'PSY_STAR_CITY', 'star city pasay'
  UNION ALL SELECT 'PSY_STAR_CITY', 'amusement park pasay'
  UNION ALL SELECT 'PSY_WORLD_TRADE_CTR', 'wtc pasay'
  UNION ALL SELECT 'PSY_WORLD_TRADE_CTR', 'world trade center pasay'
  UNION ALL SELECT 'PSY_GSIS_COMPLEX', 'gsis pasay'
  UNION ALL SELECT 'PSY_GSIS_COMPLEX', 'senate pasay'
  UNION ALL SELECT 'PSY_DFA_MAIN', 'dfa aseana pasay'
  UNION ALL SELECT 'PSY_DFA_MAIN', 'dfa pasay'
  UNION ALL SELECT 'PSY_DFA_MAIN', 'dfa macapagal'
  UNION ALL SELECT 'PSY_MACAPAGAL_BLVD', 'macapagal blvd pasay'
  UNION ALL SELECT 'PSY_MACAPAGAL_BLVD', 'macapagal pasay'
  UNION ALL SELECT 'PSY_GIL_PUYAT_EXT', 'buendia ext pasay'
  UNION ALL SELECT 'PSY_GIL_PUYAT_EXT', 'gil puyat ext pasay'
  UNION ALL SELECT 'PSY_FB_HARRISON', 'fb harrison pasay'
  UNION ALL SELECT 'PSY_FB_HARRISON', 'harrison pasay'
  UNION ALL SELECT 'PSY_DOMESTIC_RD', 'domestic road pasay'
  UNION ALL SELECT 'PSY_DOMESTIC_RD', 'naia t4 area'
  UNION ALL SELECT 'PSY_DOMESTIC_RD', 'domestic airport road'
  UNION ALL SELECT 'PSY_ANDREWS_AVE', 'andrews ave pasay'
  UNION ALL SELECT 'PSY_ANDREWS_AVE', 'newport andrews ave'
  UNION ALL SELECT 'PTR_TOWN_CENTER', 'pateros town hall'
  UNION ALL SELECT 'PTR_TOWN_CENTER', 'pateros municipal hall'
  UNION ALL SELECT 'PTR_MARKET_WAWA', 'pateros wawa market'
  UNION ALL SELECT 'PTR_MARKET_WAWA', 'wawa market pateros'
  UNION ALL SELECT 'PTR_ALMEDA_ST', 'almeda street pateros'
  UNION ALL SELECT 'PTR_ALMEDA_ST', 'm almeda pateros'
  UNION ALL SELECT 'PTR_ROSALES_ST', 'rosales pateros'
  UNION ALL SELECT 'PTR_HERRERA_ST', 'herrera street pateros'
  UNION ALL SELECT 'PTR_HERRERA_ST', 'morcilla pateros'
  UNION ALL SELECT 'PTR_BRIDGE_MAKATI', 'pateros makati bridge'
  UNION ALL SELECT 'PTR_BRIDGE_MAKATI', 'jp rizal bridge pateros'
  UNION ALL SELECT 'PTR_BRIDGE_TAGUIG', 'pateros taguig boundary'
  UNION ALL SELECT 'PTR_BRIDGE_TAGUIG', 'tuktukan pateros'
  UNION ALL SELECT 'PTR_BRIDGE_PASIG', 'pateros pasig bridge'
  UNION ALL SELECT 'PTR_BRIDGE_PASIG', 'san joaquin pateros'
  UNION ALL SELECT 'PTR_C5_EXIT', 'c5 pateros'
  UNION ALL SELECT 'PTR_C5_EXIT', 'pateros c5 road'
  UNION ALL SELECT 'PTR_SAN_ROQUE', 'san roque pateros'
  UNION ALL SELECT 'PTR_SAN_ROQUE', 'herrera brgy pateros'
  UNION ALL SELECT 'PTR_SAN_PEDRO', 'san pedro pateros'
  UNION ALL SELECT 'PTR_SAN_PEDRO', 'almeda brgy pateros'
  UNION ALL SELECT 'PTR_SAN_VICENTE', 'san vicente pateros'
  UNION ALL SELECT 'PTR_SAN_VICENTE', 'brgy san vicente pateros'
  UNION ALL SELECT 'PTR_SAN_JOSE', 'san jose pateros'
  UNION ALL SELECT 'PTR_SAN_JOSE', 'martires pateros'
  UNION ALL SELECT 'PTR_AGUHO', 'aguho pateros'
  UNION ALL SELECT 'PTR_AGUHO', 'brgy aguho pateros'
  UNION ALL SELECT 'PTR_MAGTANGGOL', 'magtanggol pateros'
  UNION ALL SELECT 'PTR_MAGTANGGOL', 'brgy magtanggol'
  UNION ALL SELECT 'PTR_TABACALERA', 'tabacalera pateros'
  UNION ALL SELECT 'PTR_TABACALERA', 'brgy tabacalera'
  UNION ALL SELECT 'PTR_SANTO_ROSARIO', 'sto rosario pateros'
  UNION ALL SELECT 'PTR_SANTO_ROSARIO', 'kanluran pateros'
  UNION ALL SELECT 'PTR_CATHOLIC_SCHOOL', 'pateros catholic school'
  UNION ALL SELECT 'PTR_TECHNOLOGICAL_COL', 'pateros tech college'
  UNION ALL SELECT 'PTR_TECHNOLOGICAL_COL', 'ptc pateros'
  UNION ALL SELECT 'ALABANG_VTX', 'vtx alabang terminal'
  UNION ALL SELECT 'ALABANG_VTX', 'vista terminal alabang'
  UNION ALL SELECT 'ALABANG_CENTRAL_STN', 'alabang central'
  UNION ALL SELECT 'ALABANG_CENTRAL_STN', 'central station alabang'
  UNION ALL SELECT 'NORTHGATE_CYBERZONE', 'northgate cyberzone alabang'
  UNION ALL SELECT 'NORTHGATE_CYBERZONE', 'northgate cyberzone muntinlupa'
  UNION ALL SELECT 'ALABANG_COMMERCIAL_CTR', 'alabang commercial'
  UNION ALL SELECT 'ALABANG_COMMERCIAL_CTR', 'alabang commercial center muntinlupa'
  UNION ALL SELECT 'CIVIC_PRIME', 'civic prime alabang'
  UNION ALL SELECT 'CIVIC_PRIME', 'civic drive alabang muntinlupa'
  UNION ALL SELECT 'ENTRATA_ALABANG', 'entrata alabang'
  UNION ALL SELECT 'ENTRATA_ALABANG', 'crimson alabang'
  UNION ALL SELECT 'ENTRATA_ALABANG', 'entrata urban complex'
  UNION ALL SELECT 'COMMERCE_AVENUE', 'commerce avenue alabang'
  UNION ALL SELECT 'COMMERCE_AVENUE', 'commerce ave alabang'
  UNION ALL SELECT 'FILINVEST_AXIS', 'filinvest axis alabang'
  UNION ALL SELECT 'FILINVEST_AXIS', 'axis towers alabang'
  UNION ALL SELECT 'MUN_NORTHGATE_CYBER', 'northgate muntinlupa pickup'
  UNION ALL SELECT 'MUN_NORTHGATE_CYBER', 'northgate main alabang'
  UNION ALL SELECT 'MUN_FILINVEST_AXIS', 'filinvest axis muntinlupa bpo'
  UNION ALL SELECT 'MUN_FILINVEST_AXIS', 'axis bpo alabang'
  UNION ALL SELECT 'MUN_WESTGATE_HUB', 'westgate commerce alabang'
  UNION ALL SELECT 'MUN_WESTGATE_HUB', 'westgate muntinlupa'
  UNION ALL SELECT 'MUN_FESTIVAL_WATER_G', 'festival water garden alabang'
  UNION ALL SELECT 'MUN_FESTIVAL_WATER_G', 'festival expansion alabang'
  UNION ALL SELECT 'MUN_AAV_MADRIGAL_GATE', 'aav madrigal gate'
  UNION ALL SELECT 'MUN_AAV_MADRIGAL_GATE', 'ayala alabang madrigal gate'
  UNION ALL SELECT 'MUN_AAV_CHAMPACA_GATE', 'aav champaca gate'
  UNION ALL SELECT 'MUN_AAV_CHAMPACA_GATE', 'ayala alabang champaca gate'
  UNION ALL SELECT 'MUN_AAV_ACACIA_GATE', 'aav acacia gate'
  UNION ALL SELECT 'MUN_AAV_ACACIA_GATE', 'ayala alabang acacia gate'
  UNION ALL SELECT 'MUN_AAV_COMMERCE_GATE', 'aav commerce gate'
  UNION ALL SELECT 'MUN_AAV_COMMERCE_GATE', 'ayala alabang commerce gate'
  UNION ALL SELECT 'MUN_ALABANG_HILLS_MAIN', 'alabang hills gate'
  UNION ALL SELECT 'MUN_ALABANG_HILLS_MAIN', 'alabang hills main gate'
  UNION ALL SELECT 'MUN_HILLSBOROUGH_GATE', 'hillsborough muntinlupa'
  UNION ALL SELECT 'MUN_HILLSBOROUGH_GATE', 'hillsborough village gate'
  UNION ALL SELECT 'MUN_ENCLAVE_ALABANG', 'enclave alabang'
  UNION ALL SELECT 'MUN_ENCLAVE_ALABANG', 'enclave daang hari'
  UNION ALL SELECT 'MUN_ALABANG_400', 'alabang 400 gate'
  UNION ALL SELECT 'MUN_ALABANG_400', 'alabang 400 village gate'
  UNION ALL SELECT 'MUN_MADRIGAL_BUSINESS', 'madrigal business park muntinlupa'
  UNION ALL SELECT 'MUN_MADRIGAL_BUSINESS', 'madrigal muntinlupa'
  UNION ALL SELECT 'MUNTINLUPA_MEDICAL_CTR', 'muntinlupa medical center'
  UNION ALL SELECT 'MUNTINLUPA_MEDICAL_CTR', 'centropolis muntinlupa'
  UNION ALL SELECT 'TUNASAN_HUB', 'tunasan muntinlupa'
  UNION ALL SELECT 'TUNASAN_HUB', 'sm center tunasan'
  UNION ALL SELECT 'POBLACION_MUNTINLUPA', 'poblacion muntinlupa'
  UNION ALL SELECT 'POBLACION_MUNTINLUPA', 'nbp area muntinlupa'
  UNION ALL SELECT 'PUTATAN_HUB', 'putatan muntinlupa'
  UNION ALL SELECT 'PUTATAN_HUB', 'putatan city hall area'
  UNION ALL SELECT 'BAYANAN_HUB', 'bayanan muntinlupa'
  UNION ALL SELECT 'BAYANAN_HUB', 'brgy bayanan muntinlupa'
  UNION ALL SELECT 'CUPANG_HUB', 'cupang muntinlupa'
  UNION ALL SELECT 'CUPANG_HUB', 'brgy cupang muntinlupa'
  UNION ALL SELECT 'CUPANG_HUB', 'wsr cupang'
  UNION ALL SELECT 'SUCAT_MUNTINLUPA_STN', 'sucat pnr muntinlupa'
  UNION ALL SELECT 'SUCAT_MUNTINLUPA_STN', 'sucat east service muntinlupa'
  UNION ALL SELECT 'ALABANG_400', 'alabang 400'
  UNION ALL SELECT 'ALABANG_400', 'alabang 400 village'
  UNION ALL SELECT 'PACITA_BOUNDARY', 'pacita complex boundary'
  UNION ALL SELECT 'PACITA_BOUNDARY', 'pacita muntinlupa'
  UNION ALL SELECT 'MCX_EXIT', 'mcx alabang'
  UNION ALL SELECT 'MCX_EXIT', 'muntinlupa cavite expressway'
  UNION ALL SELECT 'MUN_SOLDIERS_HILLS_1', 'soldiers hills 1 muntinlupa'
  UNION ALL SELECT 'MUN_SOLDIERS_HILLS_1', 'soldiers hills main'
  UNION ALL SELECT 'MUN_SOLDIERS_HILLS_2', 'soldiers hills 2 muntinlupa'
  UNION ALL SELECT 'MUN_SOLDIERS_HILLS_2', 'soldiers hills interior'
  UNION ALL SELECT 'MUN_KATARUNGAN_VILL', 'katarungan muntinlupa village'
  UNION ALL SELECT 'MUN_SM_MUNTINLUPA', 'sm muntinlupa tunasan'
  UNION ALL SELECT 'MUN_TUNASAN_MARKET', 'tunasan market muntinlupa'
  UNION ALL SELECT 'MUN_TUNASAN_MARKET', 'tunasan national road'
  UNION ALL SELECT 'MUN_SUSANA_HEIGHTS', 'susana heights muntinlupa slex'
  UNION ALL SELECT 'MUN_VICTORIA_HOMES_MAIN', 'victoria homes tunasan'
  UNION ALL SELECT 'MUN_VICTORIA_HOMES_MAIN', 'victoria homes gate'
  UNION ALL SELECT 'MUN_LINDENWOOD_RES', 'lindenwood muntinlupa'
  UNION ALL SELECT 'MUN_LINDENWOOD_RES', 'lindenwood susana heights'
  UNION ALL SELECT 'MUN_LAKEFRONT_PRESIDIO', 'the lakefront muntinlupa'
  UNION ALL SELECT 'MUN_LAKEFRONT_PRESIDIO', 'presidio sucat'
  UNION ALL SELECT 'MUN_POSADAS_SUCAT', 'posadas muntinlupa'
  UNION ALL SELECT 'MUN_POSADAS_SUCAT', 'posadas sucat gateway'
  UNION ALL SELECT 'MUN_CUPANG_BRGY_HALL', 'cupang intermodal'
  UNION ALL SELECT 'MUN_CUPANG_BRGY_HALL', 'brgy cupang intermodal'
  UNION ALL SELECT 'MUN_SOUTH_GREENHEIGHTS', 'south greenheights muntinlupa'
  UNION ALL SELECT 'MUN_NBP_SUNKEN_GARDEN', 'nbp sunken garden'
  UNION ALL SELECT 'MUN_NBP_SUNKEN_GARDEN', 'nbp reservation muntinlupa'
  UNION ALL SELECT 'MUN_PACIFIC_VILLAGE', 'pacific village muntinlupa'
  UNION ALL SELECT 'MUN_PACIFIC_VILLAGE', 'lucena st muntinlupa'
  UNION ALL SELECT 'MUN_INTERCITY_HOMES', 'intercity homes cupang'
  UNION ALL SELECT 'MUN_INTERCITY_HOMES', 'intercity cupang muntinlupa'
  UNION ALL SELECT 'MUN_SOUTHRIDGE_GATE', 'southridge muntinlupa'
  UNION ALL SELECT 'MUN_SOUTHRIDGE_GATE', 'southridge village gate'
  UNION ALL SELECT 'MUN_SANTANA_GROVE', 'santana grove muntinlupa'
  UNION ALL SELECT 'MUN_SANTANA_GROVE', 'soreena ave muntinlupa'
  UNION ALL SELECT 'MUN_PARKLANE_TUNASAN', 'parklane tunasan'
  UNION ALL SELECT 'MUN_PARKLANE_TUNASAN', 'parklane muntinlupa'
  UNION ALL SELECT 'MUN_BAGONG_TANYAG_HUB', 'bagong tanyag muntinlupa'
  UNION ALL SELECT 'MUN_BAGONG_TANYAG_HUB', 'brgy bagong tanyag'
  UNION ALL SELECT 'MUN_WSR_TRIANGLE_7', 'triangle 7 wsr'
  UNION ALL SELECT 'MUN_WSR_TRIANGLE_7', 'wsr triangle muntinlupa'
  UNION ALL SELECT 'MUN_WSR_40_KNOTS', '40 knots alabang'
  UNION ALL SELECT 'MUN_WSR_40_KNOTS', '40 knots wsr'
  UNION ALL SELECT 'MUN_WSR_40_KNOTS', 'wsr 40 knots'
  UNION ALL SELECT 'MUN_WSR_KAIJO', 'kaijo wsr muntinlupa'
  UNION ALL SELECT 'MUN_WSR_ALABANG_EXIT', 'alabang wsr exit'
  UNION ALL SELECT 'MUN_WSR_ALABANG_EXIT', 'alabang exit wsr'
  UNION ALL SELECT 'MUN_ESR_BAGONG_TANYAG', 'esr bagong tanyag'
  UNION ALL SELECT 'MUN_ESR_BAGONG_TANYAG', 'munti taguig border esr'
  UNION ALL SELECT 'MUN_ESR_SUCAT_INTER', 'esr sucat interchange'
  UNION ALL SELECT 'MUN_ESR_SUCAT_INTER', 'east service sucat'
  UNION ALL SELECT 'MUN_ESR_SUCAT_TERM', 'esr sucat terminal'
  UNION ALL SELECT 'MUN_ESR_SUCAT_TERM', 'sucat esr terminal'
  UNION ALL SELECT 'MUN_WSR_B_MAG_AREA', 'b mag area muntinlupa'
  UNION ALL SELECT 'MUN_WSR_B_MAG_AREA', 'wsr b-mag'
  UNION ALL SELECT 'MUN_MCX_JUNCTION', 'mcx slex junction'
  UNION ALL SELECT 'MUN_MCX_JUNCTION', 'slex mcx junction'
  UNION ALL SELECT 'MUN_DAANG_HARI_MUNTI', 'daang hari muntinlupa segment'
  UNION ALL SELECT 'MUN_SUCAT_PNR_STATION', 'pnr sucat station'
  UNION ALL SELECT 'MUN_TUNASAN_CITY_LIMIT', 'tunasan laguna boundary'
  UNION ALL SELECT 'MUN_TUNASAN_CITY_LIMIT', 'tunasan san pedro boundary'
  UNION ALL SELECT 'MUN_CITY_HALL_MUNTI', 'muntinlupa city hall main'
  UNION ALL SELECT 'MUN_OSMUN_HOSPITAL', 'osmun muntinlupa'
  UNION ALL SELECT 'MUN_OSMUN_HOSPITAL', 'ospital ng muntinlupa'
  UNION ALL SELECT 'SAN_BEDA_ALABANG', 'san beda college alabang'
  UNION ALL SELECT 'SAN_BEDA_ALABANG', 'sbc alabang'
  UNION ALL SELECT 'DE_LA_SALLE_ZOBEL', 'dlsz alabang'
  UNION ALL SELECT 'DE_LA_SALLE_ZOBEL', 'la salle zobel alabang'
  UNION ALL SELECT 'DE_LA_SALLE_ZOBEL', 'de la salle alabang'
  UNION ALL SELECT 'FEU_ALABANG', 'feu alabang campus'
  UNION ALL SELECT 'RESEARCH_INST_MED', 'ritm muntinlupa'
  UNION ALL SELECT 'RESEARCH_INST_MED', 'research institute tropical medicine'
  UNION ALL SELECT 'PRQ_SOLAIRE', 'solaire resort paranaque'
  UNION ALL SELECT 'PRQ_SOLAIRE', 'solaire casino paranaque'
  UNION ALL SELECT 'PRQ_CITY_OF_DREAMS', 'city of dreams paranaque'
  UNION ALL SELECT 'PRQ_CITY_OF_DREAMS', 'cod paranaque'
  UNION ALL SELECT 'PRQ_OKADA', 'okada paranaque'
  UNION ALL SELECT 'PRQ_OKADA', 'okada casino paranaque'
  UNION ALL SELECT 'PRQ_ASEANA_SQUARE', 'aseana square paranaque'
  UNION ALL SELECT 'PRQ_ASEANA_SQUARE', 'aseana city paranaque'
  UNION ALL SELECT 'PRQ_PARACAL_RD', 'paracal aseana'
  UNION ALL SELECT 'PRQ_PARACAL_RD', 'paracal road paranaque'
  UNION ALL SELECT 'PRQ_NAIA_T1', 'naia t1 paranaque'
  UNION ALL SELECT 'PRQ_NAIA_T1', 'terminal 1 paranaque'
  UNION ALL SELECT 'PRQ_NAIA_T1', 'naia terminal 1 paranaque'
  UNION ALL SELECT 'PRQ_NAIA_T2', 'naia t2 paranaque'
  UNION ALL SELECT 'PRQ_NAIA_T2', 'terminal 2 paranaque'
  UNION ALL SELECT 'PRQ_NAIA_T2', 'naia terminal 2 paranaque'
  UNION ALL SELECT 'PRQ_BACLARAN_CHURCH', 'baclaran church paranaque'
  UNION ALL SELECT 'PRQ_BACLARAN_CHURCH', 'redemptorist paranaque'
  UNION ALL SELECT 'PRQ_BACLARAN_CHURCH_HUB', 'baclaran church hub'
  UNION ALL SELECT 'PRQ_BACLARAN_CHURCH_HUB', 'redemptorist road baclaran'
  UNION ALL SELECT 'PRQ_BACLARAN_LRT', 'baclaran lrt paranaque'
  UNION ALL SELECT 'PRQ_BACLARAN_LRT', 'lrt baclaran paranaque'
  UNION ALL SELECT 'PRQ_CITY_HALL', 'paranaque city hall main'
  UNION ALL SELECT 'PRQ_CITY_HALL', 'paranaque hall'
  UNION ALL SELECT 'PRQ_PATTS', 'patts paranaque'
  UNION ALL SELECT 'PRQ_PATTS', 'patts college aeronautics'
  UNION ALL SELECT 'PRQ_SUCAT_EVANGELISTA', 'sucat evangelista paranaque'
  UNION ALL SELECT 'PRQ_SUCAT_EVANGELISTA', 'evangelista sucat road'
  UNION ALL SELECT 'PRQ_WALTMART_SUCAT', 'waltermart sucat paranaque'
  UNION ALL SELECT 'PRQ_WALTMART_SUCAT', 'waltermart paranaque'
  UNION ALL SELECT 'PRQ_BICUTAN_WSR', 'bicutan wsr paranaque'
  UNION ALL SELECT 'PRQ_BICUTAN_WSR', 'west service road bicutan'
  UNION ALL SELECT 'PRQ_BICUTAN_ESR', 'bicutan esr paranaque'
  UNION ALL SELECT 'PRQ_BICUTAN_ESR', 'east service road bicutan'
  UNION ALL SELECT 'PRQ_BICUTAN_INTERCHANGE', 'bicutan slex exit paranaque'
  UNION ALL SELECT 'PRQ_BICUTAN_INTERCHANGE', 'bicutan interchange paranaque'
  UNION ALL SELECT 'PRQ_SUCAT_INTERCHANGE', 'sucat slex exit paranaque'
  UNION ALL SELECT 'PRQ_SUCAT_INTERCHANGE', 'sucat interchange paranaque'
  UNION ALL SELECT 'PRQ_NINOY_AQUINO_AVE', 'ninoy aquino ave paranaque'
  UNION ALL SELECT 'PRQ_NINOY_AQUINO_AVE', 'naia road paranaque'
  UNION ALL SELECT 'PRQ_SUCAT_PALENGKE', 'sucat palengke paranaque'
  UNION ALL SELECT 'PRQ_SUCAT_PALENGKE', 'sucat public market'
  UNION ALL SELECT 'PRQ_LRT_DR_SANTOS', 'lrt dr santos paranaque'
  UNION ALL SELECT 'PRQ_LRT_DR_SANTOS', 'dr santos lrt paranaque'
  UNION ALL SELECT 'PRQ_SUCAT_STATION_PNR', 'sucat pnr paranaque'
  UNION ALL SELECT 'PRQ_SUCAT_STATION_PNR', 'pnr sucat paranaque'
  UNION ALL SELECT 'PRQ_SM_SUCAT_TERMINAL', 'sm sucat puv paranaque'
  UNION ALL SELECT 'PRQ_SM_SUCAT_TERMINAL', 'sm sucat terminal paranaque'
  UNION ALL SELECT 'PRQ_BICUTAN_ENTRY_SOUTH', 'bicutan slex south entry'
  UNION ALL SELECT 'PRQ_BICUTAN_ENTRY_SOUTH', 'bicutan southbound entry'
  UNION ALL SELECT 'PRQ_SUCAT_ENTRY_NORTH', 'sucat slex north entry'
  UNION ALL SELECT 'PRQ_SUCAT_ENTRY_NORTH', 'sucat northbound entry'
  UNION ALL SELECT 'PRQ_SKYWAY_SUCAT_EXIT', 'skyway sucat paranaque'
  UNION ALL SELECT 'PRQ_SKYWAY_SUCAT_EXIT', 'sucat skyway ramp'
  UNION ALL SELECT 'PRQ_BICUTAN_SLEX_EXIT', 'bicutan slex exit dost'
  UNION ALL SELECT 'PRQ_BICUTAN_SLEX_EXIT', 'dost bicutan exit'
  UNION ALL SELECT 'PRQ_SUCAT_SKYWAY_RAMP', 'sucat skyway northbound ramp'
  UNION ALL SELECT 'PRQ_DONA_SOLEDAD_SM', 'dona soledad sm bicutan'
  UNION ALL SELECT 'PRQ_DONA_SOLEDAD_SM', 'dona soledad paranaque'
  UNION ALL SELECT 'PRQ_BF_ELIZALDE', 'elizalde bf homes paranaque'
  UNION ALL SELECT 'PRQ_BF_ELIZALDE', 'bf elizalde paranaque'
  UNION ALL SELECT 'PRQ_BF_AGUIRRE', 'aguirre bf homes paranaque'
  UNION ALL SELECT 'PRQ_BF_AGUIRRE', 'bf aguirre paranaque'
  UNION ALL SELECT 'PRQ_BF_NORTH_WEST', 'bf northwest paranaque'
  UNION ALL SELECT 'PRQ_BF_NORTH_WEST', 'bf homes northwest'
  UNION ALL SELECT 'PRQ_BF_HOMES_PH_1', 'bf phase 1 paranaque'
  UNION ALL SELECT 'PRQ_BF_HOMES_PH_1', 'bf homes phase 1 paranaque'
  UNION ALL SELECT 'PRQ_BF_HOMES_PH_3', 'bf phase 3 paranaque'
  UNION ALL SELECT 'PRQ_BF_HOMES_PH_3', 'bf homes phase 3 paranaque'
  UNION ALL SELECT 'PRQ_BF_HOMES_CONCHA', 'concha cruz bf homes'
  UNION ALL SELECT 'PRQ_BF_HOMES_CONCHA', 'bf concha paranaque'
  UNION ALL SELECT 'PRQ_BF_HOMES_TROPICAL', 'tropical avenue bf homes paranaque'
  UNION ALL SELECT 'PRQ_BF_HOMES_SOUTHVILLE', 'southville bf homes paranaque'
  UNION ALL SELECT 'PRQ_BF_HOMES_SOUTHVILLE', 'bf international area paranaque'
  UNION ALL SELECT 'PRQ_BF_EL_GRANDE', 'el grande bf homes'
  UNION ALL SELECT 'PRQ_BF_EL_GRANDE', 'bf el grande paranaque'
  UNION ALL SELECT 'PRQ_BF_SOUTH_VALLEY', 'south valley bf homes'
  UNION ALL SELECT 'PRQ_BF_SOUTH_VALLEY', 'bf south valley paranaque'
  UNION ALL SELECT 'PRQ_BF_TROPICAL_AVE', 'tropical avenue bf north'
  UNION ALL SELECT 'PRQ_BF_TROPICAL_AVE', 'bf tropical paranaque'
  UNION ALL SELECT 'PRQ_BF_NORTH_GATE', 'bf homes north gate'
  UNION ALL SELECT 'PRQ_BF_NORTH_GATE', 'bf north paranaque'
  UNION ALL SELECT 'PRQ_BF_AGUIRRE_INTERIOR', 'aguirre tirona junction paranaque'
  UNION ALL SELECT 'PRQ_TIRONA_ST_HUB', 'tirona bf homes paranaque'
  UNION ALL SELECT 'PRQ_TROPICAL_PALMS', 'tropical palms paranaque'
  UNION ALL SELECT 'PRQ_TROPICAL_PALMS', 'bf homes west paranaque'
  UNION ALL SELECT 'PRQ_CAA_ROAD_MAIN', 'caa road paranaque'
  UNION ALL SELECT 'PRQ_CAA_ROAD_MAIN', 'bf international hub paranaque'
  UNION ALL SELECT 'PRQ_SOUTHVILLE_INTL', 'southville intl paranaque'
  UNION ALL SELECT 'PRQ_SOUTHVILLE_INTL', 'luxembourg st paranaque'
  UNION ALL SELECT 'PRQ_MULTINATIONAL_GATE', 'multinational village paranaque'
  UNION ALL SELECT 'PRQ_MULTINATIONAL_GATE', 'multinational gate paranaque'
  UNION ALL SELECT 'PRQ_MOONWALK_GATE', 'moonwalk village paranaque'
  UNION ALL SELECT 'PRQ_MOONWALK_GATE', 'moonwalk gate paranaque'
  UNION ALL SELECT 'PRQ_MOONWALK_TALABA', 'moonwalk talaba paranaque'
  UNION ALL SELECT 'PRQ_MOONWALK_TALABA', 'talaba moonwalk'
  UNION ALL SELECT 'PRQ_MOONWALK_PH2_GATE', 'moonwalk phase 2 paranaque'
  UNION ALL SELECT 'PRQ_MOONWALK_PH2_GATE', 'armstrong moonwalk gate'
  UNION ALL SELECT 'PRQ_ARMSTRONG_AVE', 'armstrong ave paranaque'
  UNION ALL SELECT 'PRQ_ARMSTRONG_AVE', 'armstrong moonwalk hub'
  UNION ALL SELECT 'PRQ_UNITED_PRQ', 'united paranaque'
  UNION ALL SELECT 'PRQ_UNITED_PRQ', 'up1 up2 up3 paranaque'
  UNION ALL SELECT 'PRQ_UNITED_PRQ_ESTATES', 'united paranaque estates'
  UNION ALL SELECT 'PRQ_UNITED_PRQ_ESTATES', 'up estates paranaque'
  UNION ALL SELECT 'PRQ_UNITED_PRQ_1', 'united paranaque 1 slex'
  UNION ALL SELECT 'PRQ_NOMO_SUCAT', 'nomo paranaque'
  UNION ALL SELECT 'PRQ_NOMO_SUCAT', 'vista mall sucat paranaque'
  UNION ALL SELECT 'PRQ_NOMO_TERMINAL', 'nomo pitx paranaque'
  UNION ALL SELECT 'PRQ_NOMO_TERMINAL', 'pitx nomo paranaque'
  UNION ALL SELECT 'PRQ_MARINA_BAY', 'marina bay paranaque'
  UNION ALL SELECT 'PRQ_MERVILLE_GATE', 'merville gate paranaque'
  UNION ALL SELECT 'PRQ_MERVILLE_ADVENTIST', 'merville adventist paranaque'
  UNION ALL SELECT 'PRQ_MERVILLE_ADVENTIST', 'adventist school merville'
  UNION ALL SELECT 'PRQ_MERVILLE_ADVENT', 'adventist merville paranaque'
  UNION ALL SELECT 'PRQ_MARCELLO_GREEN_VILL', 'marcelo green village paranaque'
  UNION ALL SELECT 'PRQ_MARCELLO_GREEN_VILL', 'marcelo green esr gate'
  UNION ALL SELECT 'PRQ_MARCELO_GREEN_PH1', 'marcelo green phase 1 paranaque'
  UNION ALL SELECT 'PRQ_SUN_VALLEY_PROPER', 'sun valley proper paranaque'
  UNION ALL SELECT 'PRQ_SUN_VALLEY_PROPER', 'sun valley brgy paranaque'
  UNION ALL SELECT 'PRQ_SEVERINA_DIAMOND', 'severina diamond paranaque'
  UNION ALL SELECT 'PRQ_SEVERINA_DIAMOND', 'wsr severina paranaque'
  UNION ALL SELECT 'PRQ_GATCHALIAN_HUB', 'gatchalian subd paranaque'
  UNION ALL SELECT 'PRQ_GATCHALIAN_HUB', 'gatchalian subdivision'
  UNION ALL SELECT 'PRQ_IRENEVILLE', 'ireneville subdivision paranaque'
  UNION ALL SELECT 'PRQ_IRENEVILLE', 'ireneville sucat'
  UNION ALL SELECT 'PRQ_SOUTH_ADRIATIC_ST', 'south adriatic better living paranaque'
  UNION ALL SELECT 'PRQ_VISTA_MALL_PRQ', 'vista mall global south paranaque'
  UNION ALL SELECT 'PRQ_BETTER_LIVING_MAIN', 'better living main paranaque'
  UNION ALL SELECT 'PRQ_BETTER_LIVING_PH3', 'better living phase 3'
  UNION ALL SELECT 'PRQ_BETTER_LIVING_PH3', 'france st better living'
  UNION ALL SELECT 'PRQ_BETTER_LIVING_PH4', 'better living phase 4'
  UNION ALL SELECT 'PRQ_BETTER_LIVING_PH4', 'woodridge better living'
  UNION ALL SELECT 'PRQ_BETTER_LIVING_ANNEX', 'better living annex paranaque'
  UNION ALL SELECT 'PRQ_BETTER_LIVING_ANNEX', 'annex 35 paranaque'
  UNION ALL SELECT 'PRQ_ANNEX_35_HUB', 'annex 35 better living'
  UNION ALL SELECT 'PRQ_ANNEX_35_HUB', 'better living interior paranaque'
  UNION ALL SELECT 'PRQ_DON_BOSCO_CHURCH', 'don bosco church paranaque'
  UNION ALL SELECT 'PRQ_DON_BOSCO_CHURCH', 'don bosco sun valley'
  UNION ALL SELECT 'PRQ_DON_BOSCO_MAIN', 'don bosco better living gate'
  UNION ALL SELECT 'PRQ_EURO_VILLAGE', 'eurofarma paranaque'
  UNION ALL SELECT 'PRQ_EURO_VILLAGE', 'united hills paranaque'
  UNION ALL SELECT 'PRQ_ZION_ROAD', 'zion road better living'
  UNION ALL SELECT 'PRQ_ZION_ROAD', 'zion paranaque'
  UNION ALL SELECT 'PRQ_ZION_ROAD_HUB', 'zion road hub paranaque'
  UNION ALL SELECT 'PRQ_MALUGAY_ST', 'malugay better living gate'
  UNION ALL SELECT 'PRQ_MALUGAY_GATE', 'malugay entry better living'
  UNION ALL SELECT 'PRQ_WOOD_RIDGE', 'woodridge paranaque'
  UNION ALL SELECT 'PRQ_WOOD_RIDGE', 'better living woodridge'
  UNION ALL SELECT 'PRQ_JERUSALEM_ST', 'jerusalem st better living'
  UNION ALL SELECT 'PRQ_MILAN_ST', 'milan st better living'
  UNION ALL SELECT 'PRQ_MILAN_ST', 'milan better living phase 1'
  UNION ALL SELECT 'PRQ_MARCELLA_ST', 'marcella st paranaque'
  UNION ALL SELECT 'PRQ_MARCELLA_ST', 'marcella multinational'
  UNION ALL SELECT 'PRQ_VIVA_HOMES', 'viva homes paranaque'
  UNION ALL SELECT 'PRQ_VIVA_HOMES', 'viva better living'
  UNION ALL SELECT 'PRQ_SAN_ANTONIO_VALLEY', 'san antonio valley paranaque'
  UNION ALL SELECT 'PRQ_SAN_ANTONIO_VALLEY', 'sav 1 paranaque'
  UNION ALL SELECT 'PRQ_SAN_ANTONIO_VILL_5', 'san antonio valley 5 paranaque'
  UNION ALL SELECT 'PRQ_KABIHASNAN_INTERIOR', 'kabihasnan paranaque'
  UNION ALL SELECT 'PRQ_KABIHASNAN_INTERIOR', 'san dionisio paranaque'
  UNION ALL SELECT 'PRQ_LOPEZ_VILLAGE', 'lopez village paranaque'
  UNION ALL SELECT 'PRQ_LOPEZ_VILLAGE_MAIN', 'lopez village main paranaque'
  UNION ALL SELECT 'PRQ_SAN_ISIDRO_HUB', 'san isidro paranaque'
  UNION ALL SELECT 'PRQ_SAN_ISIDRO_HUB', 'san isidro lopez paranaque'
  UNION ALL SELECT 'PRQ_PATIO_MADRIGAL', 'patio madrigal paranaque'
  UNION ALL SELECT 'PRQ_PATIO_MADRIGAL', 'roxas blvd side paranaque'
  UNION ALL SELECT 'PRQ_WSR_SUN_VALLEY', 'wsr sun valley paranaque'
  UNION ALL SELECT 'PRQ_WSR_SUN_VALLEY', 'west service road sun valley'
  UNION ALL SELECT 'PRQ_WSR_ASTRA', 'wsr astra paranaque'
  UNION ALL SELECT 'PRQ_WSR_KNOTS', 'wsr 40 knots paranaque'
  UNION ALL SELECT 'PRQ_WSR_KNOTS', 'west service road 40 knots'
  UNION ALL SELECT 'PRQ_WSR_EDISON_AVE', 'edison ave wsr paranaque'
  UNION ALL SELECT 'PRQ_WSR_EDISON_CORP', 'edison wsr bpo paranaque'
  UNION ALL SELECT 'PRQ_KM_18_WSR', 'km 18 wsr paranaque'
  UNION ALL SELECT 'PRQ_KM_18_WSR', 'km 18 west service road'
  UNION ALL SELECT 'PRQ_ESR_MARCELO_GREEN', 'esr marcelo green paranaque'
  UNION ALL SELECT 'PRQ_ESR_UNITED_PRQ', 'esr united paranaque'
  UNION ALL SELECT 'PRQ_ESR_PRYCE_GAS', 'esr pryce gas paranaque'
  UNION ALL SELECT 'PRQ_KM_21_ESR', 'km 21 esr paranaque'
  UNION ALL SELECT 'PRQ_KM_21_ESR', 'km 21 east service road bicutan'
  UNION ALL SELECT 'PRQ_SOUTH_METRO_GATE', 'south metro gate paranaque'
  UNION ALL SELECT 'PRQ_SOUTH_METRO_GATE', 'south metro wsr'
  UNION ALL SELECT 'PRQ_K_POINT_HUB', 'k point paranaque'
  UNION ALL SELECT 'PRQ_K_POINT_HUB', 'k-point wsr paranaque'
  UNION ALL SELECT 'PRQ_VALLEY_VIEW_C5', 'valley view c5 paranaque'
  UNION ALL SELECT 'PRQ_COASTAL_PLAZA', 'coastal plaza paranaque'
  UNION ALL SELECT 'PRQ_COASTAL_PLAZA', 'cavitex entry paranaque'
  UNION ALL SELECT 'PRQ_PITX_TRANSFER_NODE', 'pitx paranaque node'
  UNION ALL SELECT 'PRQ_PITX_TRANSFER_NODE', 'pitx entry paranaque'
  UNION ALL SELECT 'PRQ_QUIRINO_AVE_TAMBO', 'quirino tambo paranaque'
  UNION ALL SELECT 'PRQ_QUIRINO_AVE_TAMBO', 'tambo naia road paranaque'
  UNION ALL SELECT 'PRQ_TAMBO_HUB', 'brgy tambo paranaque'
  UNION ALL SELECT 'PRQ_LA_HUERTA', 'la huerta paranaque coastal'
  UNION ALL SELECT 'PRQ_LA_HUERTA_BRIDGE', 'la huerta bridge paranaque'
  UNION ALL SELECT 'PRQ_LA_HUERTA_BRIDGE', 'paranaque river bridge'
  UNION ALL SELECT 'PRQ_DON_GALO_HUB', 'don galo paranaque'
  UNION ALL SELECT 'PRQ_DON_GALO_HUB', 'brgy don galo coastal'
  UNION ALL SELECT 'PRQ_NAIA_RD_TERMINAL_1', 'naia terminal 1 paranaque road'
  UNION ALL SELECT 'PRQ_NAIA_RD_TERMINAL_1', 'naia road terminal paranaque'
  UNION ALL SELECT 'PRQ_AIRPORT_VILLAGE', 'airport village paranaque'
  UNION ALL SELECT 'PRQ_AIRPORT_VILLAGE', 'mia road paranaque'
  UNION ALL SELECT 'PRQ_DUTY_FREE_HUB', 'duty free fiestamall naia'
  UNION ALL SELECT 'PRQ_DUTY_FREE_HUB', 'duty free paranaque naia'
  UNION ALL SELECT 'PRQ_STO_NINO_HUB', 'sto nino paranaque'
  UNION ALL SELECT 'PRQ_STO_NINO_HUB', 'brgy sto nino paranaque'
  UNION ALL SELECT 'PRQ_GLOBAL_SOUTH_MALL', 'global south paranaque'
  UNION ALL SELECT 'PRQ_GLOBAL_SOUTH_MALL', 'villar sipag paranaque'
  UNION ALL SELECT 'PRQ_C5_EXT_FLYOVER', 'c5 flyover paranaque'
  UNION ALL SELECT 'PRQ_C5_EXT_FLYOVER', 'merville flyover paranaque'
  UNION ALL SELECT 'PRQ_C5_EXT_SHELL', 'c5 shell paranaque'
  UNION ALL SELECT 'PRQ_C5_EXT_SHELL', 'c5 commercial paranaque'
  UNION ALL SELECT 'PRQ_CARLOS_P_GARCIA', 'cp garcia paranaque'
  UNION ALL SELECT 'PRQ_CARLOS_P_GARCIA', 'pulang lupa uno paranaque'
  UNION ALL SELECT 'PRQ_OLIVAREZ_COLLEGE', 'olivarez college'
  UNION ALL SELECT 'PRQ_OLIVAREZ_COLLEGE', 'olivarez paranaque college'
  UNION ALL SELECT 'PRQ_OLIVAREZ_HOSPITAL', 'olivarez general hospital paranaque'
  UNION ALL SELECT 'PRQ_OLIVAREZ_HOSPITAL', 'olivarez hospital paranaque'
  UNION ALL SELECT 'PRQ_PREMIERE_MED_CTR', 'premiere medical paranaque'
  UNION ALL SELECT 'PRQ_PREMIERE_MED_CTR', 'medical center paranaque sucat'
  UNION ALL SELECT 'PRQ_MANILA_MEMORIAL', 'manila memorial paranaque'
  UNION ALL SELECT 'PRQ_MANILA_MEMORIAL', 'manila memorial sucat'
  UNION ALL SELECT 'PRQ_LOYOLA_MEMORIAL', 'loyola memorial paranaque'
  UNION ALL SELECT 'PRQ_LOYOLA_MEMORIAL', 'loyola memorial sucat'
  UNION ALL SELECT 'PRQ_ST_ANDREW_SCHOOL', 'st andrews paranaque'
  UNION ALL SELECT 'PRQ_ST_ANDREW_SCHOOL', 'st andrews school paranaque'
  UNION ALL SELECT 'LP_SM_CENTER', 'sm las pinas'
  UNION ALL SELECT 'LP_SM_CENTER', 'sm center lp'
  UNION ALL SELECT 'LP_SM_CENTER', 'sm center las pinas'
  UNION ALL SELECT 'LP_VISTA_MALL', 'vista mall lp'
  UNION ALL SELECT 'LP_VISTA_MALL', 'vista las pinas'
  UNION ALL SELECT 'LP_LANDMARK_ALABANG_W', 'landmark las pinas'
  UNION ALL SELECT 'LP_LANDMARK_ALABANG_W', 'alabang west las pinas'
  UNION ALL SELECT 'LP_STAR_AVENUE', 'cv starr las pinas'
  UNION ALL SELECT 'LP_STAR_AVENUE', 'starr avenue las pinas'
  UNION ALL SELECT 'LP_STAR_AVENUE', 'philamlife las pinas'
  UNION ALL SELECT 'LP_VISTA_GLOBAL_SOUTH', 'global south las pinas'
  UNION ALL SELECT 'LP_VISTA_GLOBAL_SOUTH', 'c5 ext global south'
  UNION ALL SELECT 'LP_SOUTH_MALL_TERMINAL', 'sm south mall terminal'
  UNION ALL SELECT 'LP_SOUTH_MALL_TERMINAL', 'south mall las pinas terminal'
  UNION ALL SELECT 'LP_BF_CAA_GATE', 'bf international las pinas'
  UNION ALL SELECT 'LP_BF_CAA_GATE', 'caa gate las pinas'
  UNION ALL SELECT 'LP_BF_RESORT_DRIVE', 'bf resort drive las pinas'
  UNION ALL SELECT 'LP_BF_RESORT_DRIVE', 'bfrd las pinas'
  UNION ALL SELECT 'LP_BF_TROPICAL_PALMS', 'bf tropical palms las pinas'
  UNION ALL SELECT 'LP_BF_SOUTH_VILLE', 'southville las pinas'
  UNION ALL SELECT 'LP_BF_SOUTH_VILLE', 'bf southville las pinas'
  UNION ALL SELECT 'LP_BF_ALMANZA_MAIN', 'bf almanza las pinas'
  UNION ALL SELECT 'LP_BF_ALMANZA_MAIN', 'bf almanza gate'
  UNION ALL SELECT 'LP_BF_ALMANZA_REGALADO', 'regalado bf almanza'
  UNION ALL SELECT 'LP_BF_ALMANZA_REGALADO', 'bf almanza regalado'
  UNION ALL SELECT 'LP_BF_RESORT_CLUBHOUSE', 'bf resort clubhouse las pinas'
  UNION ALL SELECT 'LP_BF_RESORT_CLUBHOUSE', 'bfr clubhouse'
  UNION ALL SELECT 'LP_BF_RESORT_ONX', 'onix st bf resort'
  UNION ALL SELECT 'LP_BF_RESORT_ONX', 'onix bf las pinas'
  UNION ALL SELECT 'LP_BF_THAI_HUB', 'bf thai las pinas'
  UNION ALL SELECT 'LP_BF_THAI_HUB', 'tropical avenue bf las pinas'
  UNION ALL SELECT 'LP_ENCLAVE_ALABANG', 'enclave almanza'
  UNION ALL SELECT 'LP_ENCLAVE_ALABANG', 'enclave las pinas'
  UNION ALL SELECT 'LP_PILAR_EXECUTIVE', 'pilar executive village'
  UNION ALL SELECT 'LP_PILAR_EXECUTIVE', 'pilar exec las pinas'
  UNION ALL SELECT 'LP_GREAT_CHURCH_LP', 'great church las pinas'
  UNION ALL SELECT 'LP_GREAT_CHURCH_LP', 'bf resort great church'
  UNION ALL SELECT 'LP_PILAR_VILLAGE', 'pilar village las pinas'
  UNION ALL SELECT 'LP_PILAR_VILLAGE', 'pilar commercial las pinas'
  UNION ALL SELECT 'LP_PILAR_VILLAGE_SOUTH', 'pilar village south gate'
  UNION ALL SELECT 'LP_PILAR_VILLAGE_SOUTH', 'pilar south almanza'
  UNION ALL SELECT 'LP_PILAR_CHURCH_HUB', 'holy family parish las pinas'
  UNION ALL SELECT 'LP_PILAR_CHURCH_HUB', 'pilar church las pinas'
  UNION ALL SELECT 'LP_TS_CRUZ_GATE', 'ts cruz las pinas'
  UNION ALL SELECT 'LP_TS_CRUZ_GATE', 'ts cruz subdivision gate'
  UNION ALL SELECT 'LP_MOONWALK_LP', 'moonwalk las pinas village'
  UNION ALL SELECT 'LP_MOONWALK_LP_INTERIOR', 'moonwalk ph 2 las pinas'
  UNION ALL SELECT 'LP_MOONWALK_LP_INTERIOR', 'moonwalk interior las pinas'
  UNION ALL SELECT 'LP_MANUELA_VILLAGE', 'manuela las pinas'
  UNION ALL SELECT 'LP_MANUELA_VILLAGE', 'manuela pamplona'
  UNION ALL SELECT 'LP_MANUELA_1_HUB', 'manuela 1 las pinas'
  UNION ALL SELECT 'LP_MANUELA_1_HUB', 'manuela real st las pinas'
  UNION ALL SELECT 'LP_MANUELA_4_GATE', 'manuela 4 las pinas'
  UNION ALL SELECT 'LP_MANUELA_4_GATE', 'pamplona tres gate'
  UNION ALL SELECT 'LP_GOLDEN_GATE', 'golden gate las pinas subd'
  UNION ALL SELECT 'LP_GOLDEN_GATE_LP', 'golden gate talon tres'
  UNION ALL SELECT 'LP_GOLDEN_GATE_LP', 'golden gate subd las pinas'
  UNION ALL SELECT 'LP_VERA_VILLE', 'vera ville las pinas'
  UNION ALL SELECT 'LP_VERA_VILLE', 'veraville las pinas'
  UNION ALL SELECT 'LP_VERAVILLE_HUB', 'veraville homes las pinas'
  UNION ALL SELECT 'LP_CAA_MAIN_HUB', 'caa las pinas'
  UNION ALL SELECT 'LP_CAA_MAIN_HUB', 'brgy caa las pinas'
  UNION ALL SELECT 'LP_CAA_RD_HUB', 'caa road las pinas'
  UNION ALL SELECT 'LP_CAA_RD_HUB', 'bf international road las pinas'
  UNION ALL SELECT 'LP_CASIMIRO_VILLAGE', 'casimiro village las pinas'
  UNION ALL SELECT 'LP_CASIMIRO_VILLAGE', 'casimiro gate las pinas'
  UNION ALL SELECT 'LP_PAMPLONA_CENTRAL', 'pamplona uno las pinas'
  UNION ALL SELECT 'LP_PAMPLONA_CENTRAL', 'pamplona central hub'
  UNION ALL SELECT 'LP_ZAPOTE_BRIDGE', 'zapote bridge las pinas bacoor'
  UNION ALL SELECT 'LP_CASIMIRO_AVE', 'casimiro avenue las pinas'
  UNION ALL SELECT 'LP_CASIMIRO_AVE', 'casimiro diego cera'
  UNION ALL SELECT 'LP_VILLAREAL_ST', 'villareal las pinas'
  UNION ALL SELECT 'LP_VILLAREAL_ST', 'las pinas paranaque boundary'
  UNION ALL SELECT 'LP_FRUTO_SANTOS', 'fruto santos las pinas'
  UNION ALL SELECT 'LP_TALABA_DIVERSION', 'talaba diversion las pinas'
  UNION ALL SELECT 'LP_TALABA_DIVERSION', 'las pinas talaba road'
  UNION ALL SELECT 'LP_DIEGO_CERA_AVE', 'diego cera las pinas'
  UNION ALL SELECT 'LP_DIEGO_CERA_AVE', 'padre diego cera'
  UNION ALL SELECT 'LP_MARCOS_ALVAREZ_HUB', 'marcos alvarez moonwalk las pinas'
  UNION ALL SELECT 'LP_MARCOS_ALVAREZ_RD', 'marcos alvarez avenue las pinas'
  UNION ALL SELECT 'LP_MARCOS_ALVAREZ_ENTRY', 'marcos alvarez alabang zapote'
  UNION ALL SELECT 'LP_MARCOS_ALVAREZ_ENTRY', 'marcos alvarez entry las pinas'
  UNION ALL SELECT 'LP_C5_EXT_FLYOVER', 'c5 ext flyover las pinas'
  UNION ALL SELECT 'LP_C5_EXT_FLYOVER', 'quirino flyover las pinas'
  UNION ALL SELECT 'LP_C5_EXT_LP_EXIT', 'c5 extension las pinas exit'
  UNION ALL SELECT 'LP_VILLAR_SIPAG', 'villar sipag las pinas'
  UNION ALL SELECT 'LP_VILLAR_SIPAG', 'sipag las pinas'
  UNION ALL SELECT 'LP_VILLAR_CITY_LP', 'villar city las pinas entrance'
  UNION ALL SELECT 'LP_GULOT_AREA', 'gulot las pinas'
  UNION ALL SELECT 'LP_GULOT_AREA', 'pulanglupa uno las pinas'
  UNION ALL SELECT 'LP_CARMEL_GATE', 'carmel village las pinas'
  UNION ALL SELECT 'LP_CARMEL_GATE', 'carmel c5 ext las pinas'
  UNION ALL SELECT 'LP_GLOBAL_SOUTH_C5', 'global south c5 las pinas'
  UNION ALL SELECT 'LP_GLOBAL_SOUTH_C5', 'c5 ext gateway las pinas'
  UNION ALL SELECT 'LP_PULANGLUPA_UNO', 'pulang lupa uno las pinas'
  UNION ALL SELECT 'LP_PULANGLUPA_UNO', 'quirino pulang lupa'
  UNION ALL SELECT 'LP_TRAMO_LP_HUB', 'tramo las pinas'
  UNION ALL SELECT 'LP_TRAMO_LP_HUB', 'padre diego cera tramo'
  UNION ALL SELECT 'LP_QUIRINO_AVE_LP', 'quirino avenue las pinas'
  UNION ALL SELECT 'LP_SMC_GLOBAL_SOUTH', 'smc global south las pinas'
  UNION ALL SELECT 'LP_SMC_GLOBAL_SOUTH', 'redoliant las pinas'
  UNION ALL SELECT 'LP_ZAPOTE_KALIN_GATE', 'zapote kalinisan las pinas'
  UNION ALL SELECT 'LP_FLYOVER_ALABANG_ZAP', 'alabang zapote flyover las pinas'
  UNION ALL SELECT 'LP_FLYOVER_ALABANG_ZAP', 'casimiro flyover las pinas'
  UNION ALL SELECT 'LP_CONCHA_CRUZ_DRIVE', 'concha cruz las pinas'
  UNION ALL SELECT 'LP_CONCHA_CRUZ_DRIVE', 'madrigal boundary las pinas'
  UNION ALL SELECT 'LP_LONGOS_FLYOVER', 'longos flyover las pinas'
  UNION ALL SELECT 'LP_LONGOS_FLYOVER', 'talaba junction las pinas'
  UNION ALL SELECT 'LP_ALMANZA_UNO_HUB', 'almanza uno hub'
  UNION ALL SELECT 'LP_ALMANZA_UNO_HUB', 'almanza 1 hub'
  UNION ALL SELECT 'LP_ALMANZA_DOS_HUB', 'almanza dos hub'
  UNION ALL SELECT 'LP_ALMANZA_DOS_HUB', 'almanza 2 hub'
  UNION ALL SELECT 'LP_ALMANZA_DOS_HUB', 'daang hari almanza'
  UNION ALL SELECT 'LP_DAANG_HARI_LP_EXIT', 'daang hari las pinas side'
  UNION ALL SELECT 'LP_EVIA_LIFESTYLE_LP', 'evia lc lp boundary'
  UNION ALL SELECT 'LP_EVIA_LIFESTYLE_LP', 'evia las pinas boundary'
  UNION ALL SELECT 'LP_FORREST_A_LP', 'forresta las pinas'
  UNION ALL SELECT 'LP_FORREST_A_LP', 'villar land daang hari'
  UNION ALL SELECT 'LP_SOMERSET_LP', 'somerset almanza dos'
  UNION ALL SELECT 'LP_SOMERSET_LP', 'somerset las pinas'
  UNION ALL SELECT 'LP_TALON_KUATRO_HUB', 'talon 4 las pinas'
  UNION ALL SELECT 'LP_TALON_KUATRO_HUB', 'talon kuatro las pinas'
  UNION ALL SELECT 'LP_TALON_KUATRO_HUB', 'j aguilar las pinas'
  UNION ALL SELECT 'LP_TALON_SINGKO_HUB', 'talon 5 las pinas'
  UNION ALL SELECT 'LP_TALON_SINGKO_HUB', 'talon singko las pinas'
  UNION ALL SELECT 'LP_TALON_SINGKO_HUB', 'marcos alvarez ext las pinas'
  UNION ALL SELECT 'LP_TALON_2_COMMERCIAL', 'talon dos commercial'
  UNION ALL SELECT 'LP_TALON_2_COMMERCIAL', 'talon 2 las pinas'
  UNION ALL SELECT 'LP_BAMBOO_ORGAN', 'bamboo organ las pinas'
  UNION ALL SELECT 'LP_BAMBOO_ORGAN', 'st joseph bamboo organ'
  UNION ALL SELECT 'LP_BAMBOO_ORGAN', 'bamboo organ church'
  UNION ALL SELECT 'LP_SARAO_MOTORS', 'sarao factory las pinas'
  UNION ALL SELECT 'LP_SARAO_MOTORS', 'sarao motors factory'
  UNION ALL SELECT 'LP_GEN_HOSPITAL', 'las pinas general hospital'
  UNION ALL SELECT 'LP_GEN_HOSPITAL', 'general hospital las pinas'
  UNION ALL SELECT 'LP_LAS_PINAS_DOCTORS', 'las pinas doctors hospital'
  UNION ALL SELECT 'LP_LP_DOCTORS_HOSP', 'las pinas doctors caa rd'
  UNION ALL SELECT 'LP_UPHSD_CAMPUS', 'uphsd las pinas'
  UNION ALL SELECT 'LP_UPHSD_CAMPUS', 'perpetual help las pinas campus'
  UNION ALL SELECT 'LP_PERP_HELP_MED', 'uph dalta las pinas'
  UNION ALL SELECT 'LP_PERP_HELP_MED', 'dalta medical las pinas'
  UNION ALL SELECT 'LP_SOUTHVILLE_INTL', 'southville las pinas luxembourg'
  UNION ALL SELECT 'LP_ST_FRANCIS_ASSISI', 'st francis las pinas'
  UNION ALL SELECT 'LP_ST_FRANCIS_ASSISI', 'sfa college las pinas'
  UNION ALL SELECT 'LP_CHRIST_THE_KING_LP', 'christ the king las pinas'
  UNION ALL SELECT 'LP_CHRIST_THE_KING_LP', 'pamplona church las pinas'
  UNION ALL SELECT 'LP_CITY_HALL', 'las pinas city hall hub'
  UNION ALL SELECT 'LP_STI_LAS_PINAS', 'sti las pinas campus'
  UNION ALL SELECT 'LP_POPE_JOHN_PAUL', 'pope john paul las pinas'
  UNION ALL SELECT 'LP_POPE_JOHN_PAUL', 'pope john paul hospital'
  UNION ALL SELECT 'LP_ST_DOMINIC', 'st dominic las pinas'
  UNION ALL SELECT 'LP_ST_DOMINIC', 'st dominic medical las pinas'
) AS v ON h.code = v.hub_code
WHERE h.code IS NOT NULL;
